# -*- coding: utf-8 -*-
"""
# @Time    : 2025/12/1 16:10
# @Author  : cuils
# @Description:
"""
from .query_rewrite import REWRITE_QUERY_PROMPT, MULTI_TURN_REWRITE_QUERY_PROMPT
from .augment_generate import DIRECT_AUGMENT_GENERATE_PROMPT, MULTI_TURN_DIRECT_AUGMENT_GENERATE_PROMPT
from .continue_retrieve import CONTINUE_RETRIEVE_PROMPT
from .translate import TRANSLATION_CRITIC_PROMPT, TRANSLATION_GENERATE_PROMPT
from .data_quality_evaluate import DATA_QUALITY_EVALUATE_PROMPT


__all__ = [
    "CONTINUE_RETRIEVE_PROMPT",
    "DATA_QUALITY_EVALUATE_PROMPT",
    "DIRECT_AUGMENT_GENERATE_PROMPT",
    "MULTI_TURN_DIRECT_AUGMENT_GENERATE_PROMPT",
    "REWRITE_QUERY_PROMPT",
    "MULTI_TURN_REWRITE_QUERY_PROMPT",
    "TRANSLATION_CRITIC_PROMPT",
    "TRANSLATION_GENERATE_PROMPT"
]
