"""Stage 6: Cross-File Edge Generation and Total Graph Building.

This stage is the key differentiator of the new --all workflow:
1. Loads all subgraph data (nodes.jsonl + edges.jsonl) from each role category
2. Reads the merged edges from the root edges.jsonl (written after Stage 5 merge)
3. Classifies all edges by category:
   - Intra-Type: same file type (generated in Stage 4 by language plugins)
   - Cross-Type: same layer, different file types (generated by CrossFilePlugins)
   - Cross-Layer: different layers (generated by CrossFilePlugins)
4. Calls CrossFilePlugins only for Cross-Type and Cross-Layer patterns
5. Merges plugin results with the intra-type edges from the merged graph
6. Builds and writes the total graph

For --singlefile mode: only loads related subgraphs and produces cross-file edges
for the specified type.
"""

import json
from pathlib import Path
from typing import Optional

from classify import LAYER_METADATA, classify_project_files

# Import file type helpers
from plugins.cross_file.constants import (
    get_file_type,
    get_layer_from_path,
    CrossFileEdgeCategory,
    CROSS_FILE_EDGE_TYPES,
)

# Import edge quality / pruning utilities
try:
    from edge_quality import (
        prune_disconnected_components,
        collect_entry_points,
    )
except ImportError:
    import sys
    _scripts = Path(__file__).resolve().parent
    if str(_scripts) not in sys.path:
        sys.path.insert(0, str(_scripts))
    from edge_quality import (
        prune_disconnected_components,
        collect_entry_points,
    )


def _load_jsonl(path: Path) -> list[dict]:
    """Load records from a .jsonl file (one JSON object per line)."""
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _classify_merged_edge(
    edge: dict, qname_to_file: dict[str, str]
) -> Optional[dict]:
    """Classify a single edge from the merged graph into an Intra-Type cross-file edge.

    Returns a cross-file edge dict if the edge qualifies as intra-type, else None.
    An Intra-Type edge connects two different files of the same type (e.g., py→py imports,
    js→js imports, java→java extends).

    Source file comes from edge["file"]; target file comes from qname_to_file[to_qname].

    Qualifies when:
    - from_file and to_file both resolve to real file paths
    - Both files are in the same layer
    - Both files have the same type
    - The edge kind is one of the import/call/extends kinds that indicate cross-file references
    """
    # Intra-Type kinds: edges that represent cross-file *structural* dependencies
    # at compile/link time (NOT runtime call graph).
    # An Intra-Type edge connects two different files of the same type through
    # explicit structural relationships: import declarations or inheritance.
    _INTRA_TYPE_KINDS = frozenset((
        # Import/dependency edges (from language plugins)
        "imports", "extends", "implements",
        "jsp_include", "cpp_include", "c_include",
        # Java-specific inheritance
        "java_extends", "java_implements",
    ))

    kind = edge.get("kind", "")

    # Source file: edges from Stage 4 store it in the "file" field
    from_file = edge.get("file", "")
    # Target file: resolve via qname -> file mapping from the node index
    to_qname = edge.get("to_qname", "")
    to_file = qname_to_file.get(to_qname, "")

    if not from_file or not to_file:
        return None

    if from_file == to_file:
        return None  # same-file edge (internal), not cross-file

    from_layer = get_layer_from_path(from_file)
    to_layer = get_layer_from_path(to_file)

    if from_layer != to_layer:
        return None

    from_type = get_file_type(from_file)
    to_type = get_file_type(to_file)

    if from_type != to_type:
        return None

    # Only include edges that represent cross-file references
    if kind not in _INTRA_TYPE_KINDS:
        return None

    return {
        "from_qname": edge.get("from_qname", ""),
        "to_qname": to_qname,
        "from_file": from_file,
        "to_file": to_file,
        "from_layer": from_layer,
        "to_layer": to_layer,
        "from_type": from_type,
        "to_type": to_type,
        "kind": kind,
        "category": "intra_type",
    }



# ── Cross-file edge model ──────────────────────────────────────────────────────


def _node_to_symbol(node: dict) -> dict:
    """Convert a node dict (from nodes.jsonl) to a symbol dict with qualified_name.

    Nodes from _write_jsonl_from_graph: use 'id' = 'file::{path}' and 'label'
    Nodes from template/config handlers: use 'qualified_name'
    We preserve the full qname for cross-file lookups.

    lang field is preserved from the original node (from the language plugin).
    If absent, we derive it from the file extension.
    """
    qname = node.get("qualified_name") or node.get("id", "")
    start_val = node.get("start")
    line_num = start_val[0] if start_val else 1
    lang = node.get("lang", "")
    if not lang:
        lang = _infer_lang_from_file(node.get("file", ""))
    return {
        "qualified_name": qname,
        "name": node.get("label", ""),
        "kind": node.get("kind", "unknown"),
        "file": node.get("file", ""),
        "line": line_num,
        "lang": lang,
        "scope": node.get("scope", ""),
        "type_hint": node.get("type_hint"),
        "modifiers": node.get("modifiers", []),
        "annotations": node.get("annotations", []),
        "docstring": node.get("docstring"),
        "start": node.get("start", (1, 0)),
        "end": node.get("end", (1, 0)),
    }


def _infer_lang_from_file(file_path: str) -> str:
    """Derive language from file extension."""
    if not file_path:
        return ""
    import os
    _, ext = os.path.splitext(file_path.lower())
    mapping = {
        ".py": "python",
        ".js": "javascript",
        ".jsx": "javascript",
        ".ts": "javascript",
        ".tsx": "javascript",
        ".vue": "vue",
        ".java": "java",
        ".go": "go",
        ".rs": "rust",
        ".cpp": "cpp",
        ".c": "c",
        ".h": "c",
        ".hpp": "cpp",
        ".cs": "csharp",
        ".rb": "ruby",
        ".php": "php",
        ".swift": "swift",
        ".kt": "kotlin",
        ".scala": "scala",
        ".xml": "xml",
        ".html": "html",
        ".css": "css",
        ".scss": "css",
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".md": "markdown",
        ".sql": "sql",
        ".sh": "shell",
        ".bash": "shell",
        ".ps1": "powershell",
    }
    return mapping.get(ext, "")


def _extract_file_from_qname(qname: str) -> str:
    """Extract file path from a qname that may have a prefix like template::, file::, config::.

    Examples:
        "template::/path/to/file.jsp" → "/path/to/file.jsp"
        "config::/path/to/web.xml" → "/path/to/web.xml"
        "template::/path/to/file.vue#66" → "/path/to/file.vue" (strips line suffix)
        "jp.co.rct.jj.action.JJ901ABTEST001Action" → "" (no prefix, no file)
    """
    if not qname:
        return ""

    # Strip line number suffix (#66) first
    if "#" in qname:
        qname = qname.split("#", 1)[0]

    # Check for known prefixes
    for prefix in ("template::", "file::", "config::", "url::", "tag::", "fn::", "ext::"):
        if qname.startswith(prefix):
            return qname[len(prefix):]

    return ""


def _infer_type_from_qname(qname: str) -> str:
    """Infer file type from a qname that may contain file path or class name.

    Examples:
        "/path/to/file.java" → "java"
        "jp.co.rct.jj.action.JJ901ABTEST001Action" → "java" (Java package dots)
        "template::/path/to/file.jsp" → "jsp"
        "src.server.chat.ChatResponse" → "python" (src/ prefix → Python module)
        "scripts.generate_test_report" → "python"
    """
    if not qname:
        return ""

    # Extract file path if there's a prefix
    file_path = _extract_file_from_qname(qname)

    # If we have a file path, get extension
    if file_path:
        import os
        _, ext = os.path.splitext(file_path)
        if ext:
            return ext.lstrip(".").lower()

    # Check for Python module qname patterns (src., scripts., tests., lib.)
    # These have dots but are NOT Java packages
    python_qname_prefixes = (
        "src.", "scripts.", "tests.", "test.", "lib.", "setup.",
        "tests.", "docs.", "examples.", "tools.", "apps.",
    )
    if "." in qname and qname[0].isalpha():
        # Check if it looks like a Python module path (starts with known Python dir prefixes)
        if any(qname.startswith(p) for p in python_qname_prefixes):
            return "python"
        # For other dotted names, assume Java (has package dots like jp.co., org., com.)
        return "java"

    return ""

def make_cross_file_edge(
    kind: str,
    from_node: str,
    to_node: str,
    from_file: str,
    to_file: str,
    from_layer: str,
    to_layer: str,
    category: str,  # "same_layer" or "cross_layer"
    evidence: str = "",
    line: int = 0,
) -> dict:
    """Create a cross-file edge dict."""
    return {
        "kind": kind,
        "from_node": from_node,
        "to_node": to_node,
        "from_file": from_file,
        "to_file": to_file,
        "from_layer": from_layer,
        "to_layer": to_layer,
        "category": category,
        "evidence": evidence,
        "line": line,
        "edge_type": CROSS_FILE_EDGE_TYPES.get(kind, kind),
    }


# ── Subgraph loading ───────────────────────────────────────────────────────────

def _reconstruct_elements(nodes: list[dict]) -> dict:
    """Reconstruct template/config entry data from nodes.jsonl for cross-file plugins.

    Instead of a separate stage1b_ui.json, element data (JSP, TLD, dicon, etc.)
    is embedded directly in the node dicts. This function extracts it back into
    the dict-of-lists format that cross-file plugins expect.

    Node kinds that map to entries:
      - template_page, jsp_*         → "templates" / "jsp"
      - tld_tag                       → "tld"
      - web_xml_*                     → "xml" (web_xml)
      - dicon_component, dicon_include → "dicon"
      - servlet_def, servlet_mapping   → merged into "xml"
      - filter_def, filter_mapping     → merged into "xml"
    """
    result: dict = {"templates": []}

    # Group template-file nodes by their file
    template_files: dict[str, list] = {}
    tld_entries: list = []
    web_xml_entries: list = []
    dicon_entries: list = []
    result_map_entries: list = []

    for node in nodes:
        kind = node.get("kind", "")
        fp = node.get("file", "") or ""
        line = (node.get("start", [1, 0])[0] if node.get("start") else 1)
        attrs = node.get("attrs", {})

        # Template files and their elements
        # NOTE: Order matters! Check elements BEFORE template_page to avoid
        # jsp_custom_tag etc. being captured by the first condition but with empty elements
        if kind in ("jsp_expression", "jsp_form_field", "jsp_custom_tag",
                    "jsp_struts_action", "jsp_include", "jsp_directive"):
            tag_name = node.get("tag_name", "")
            if fp not in template_files:
                template_files[fp] = {
                    "file": fp,
                    "elements": [],
                    "parse_error": False,
                }
            template_files[fp]["elements"].append({
                "name": node.get("name", tag_name),
                "kind": kind,
                "line": line,
                "tag_name": tag_name,
                "attrs": attrs,
            })
        elif kind == "template_page":
            if fp not in template_files:
                template_files[fp] = {
                    "file": fp,
                    "elements": [],
                    "parse_error": False,
                }

        # TLD tags - need to track which TLD file they belong to
        elif kind == "tld_tag":
            # Extract TLD file from the node's file path (node.file is the TLD file)
            tld_file = fp
            # Use label as name since name field is often empty
            # Label format: "prefix:tagname" like "c_rt:param"
            tag_label = node.get("label", "")
            tag_name = node.get("name", tag_label)
            if not tag_name:
                tag_name = tag_label
            # Use class_name for compatibility with tld_handler plugin
            tld_entries.append({
                "name": tag_name,
                "class_name": attrs.get("class_name", ""),
                "line": line,
                "file": tld_file,
                "entry_type": "tld_tag",  # Required by _find_defined_tags
                "attrs": attrs,
            })

        # Web XML elements
        elif kind in ("servlet_def", "servlet_mapping", "filter_def",
                      "filter_mapping", "jsp_property_group", "config_file"):
            web_xml_entries.append({
                "entry_type": kind,
                "name": node.get("name", attrs.get("name", attrs.get("servlet_name", ""))),
                "class_name": attrs.get("class_name", attrs.get("servlet_class", "")),
                "line": line,
                "attrs": attrs,
            })

        # Dicon components
        elif kind in ("dicon_component", "dicon_include"):
            dicon_entries.append({
                "name": node.get("name", attrs.get("name", "")),
                "class_name": attrs.get("class_name", ""),
                "line": line,
            })

        # MyBatis XML Mapper result_map entries
        elif kind == "result_map":
            # class_name in attrs holds the Java entity type (from XML type="pkg.Entity")
            java_type = attrs.get("class_name", "")
            result_map_entries.append({
                "entry_type": "result_map",
                "name": node.get("name", ""),
                "java_type": java_type,
                "line": line,
                "attrs": attrs,
                "file": fp,
            })

    # Convert template_files dict → list
    result["templates"] = list(template_files.values())
    result["jsp"] = list(template_files.values())  # alias

    # Group tld_entries by their file
    tld_by_file: dict[str, list] = {}
    for tld_entry in tld_entries:
        tld_file = tld_entry.get("file", "")
        if tld_file not in tld_by_file:
            tld_by_file[tld_file] = []
        tld_by_file[tld_file].append(tld_entry)

    if tld_by_file:
        result["tld"] = [{"file": f, "entries": entries} for f, entries in tld_by_file.items()]
    if web_xml_entries:
        result["xml"] = [{"entries": web_xml_entries, "file": "", "config_type": "web_xml"}]
    if dicon_entries:
        result["dicon"] = [{"entries": dicon_entries, "file": ""}]
    if result_map_entries:
        result["result_maps"] = [{"entries": result_map_entries, "file": ""}]

    return result


def load_subgraph(subgraph_dir: Path) -> tuple[list[dict], list[dict]]:
    """Load nodes and edges from a subgraph directory.

    Returns:
        (nodes, edges) loaded from nodes.jsonl and edges.jsonl
    """
    nodes: list[dict] = []
    edges: list[dict] = []

    nodes_file = subgraph_dir / "nodes.jsonl"
    if nodes_file.exists():
        for line in nodes_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                nodes.append(json.loads(line))

    edges_file = subgraph_dir / "edges.jsonl"
    if edges_file.exists():
        for line in edges_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                edges.append(json.loads(line))

    return nodes, edges


def load_elements(subgraph_dir: Path) -> dict:
    """Load template/config element data from a subgraph directory.

    Priority:
    1. stage1b_ui.json (old pipeline format — contains parsed elements with attrs)
    2. Reconstruct from nodes.jsonl (new pipeline — elements embedded in nodes)

    Returns:
        Element dict with keys like "templates", "jsp", "tld", "dicon", etc.
    """
    ui_file = subgraph_dir / "stage1b_ui.json"
    if ui_file.exists():
        try:
            return json.loads(ui_file.read_text(encoding="utf-8"))
        except Exception:
            pass

    # Fallback: reconstruct from nodes
    nodes, _ = load_subgraph(subgraph_dir)
    return _reconstruct_elements(nodes)


def load_all_subgraphs(role_dir: Path) -> dict[str, tuple[list[dict], list[dict]]]:
    """Load all subgraphs from a role directory.

    Args:
        role_dir: Root output directory (e.g. output/01_source/backend/)

    Returns:
        Dict mapping subgraph_name -> (nodes, edges)
    """
    subgraphs: dict[str, tuple[list[dict], list[dict]]] = {}

    if not role_dir.exists():
        return subgraphs

    for subdir in role_dir.iterdir():
        if subdir.is_dir():
            nodes, edges = load_subgraph(subdir)
            if nodes or edges:
                subgraphs[subdir.name] = (nodes, edges)

    return subgraphs


# ── Cross-file edge generation ───────────────────────────────────────────────

def _load_cross_file_plugins():
    """Lazy-load CrossFilePlugin implementations."""
    try:
        from plugins.cross_file import CrossFileRegistry
        return CrossFileRegistry
    except ImportError:
        return None


def produce_cross_file_edges(
    subgraphs: dict[str, tuple[list[dict], list[dict]]],
    all_symbols: list[dict],
    merged_elements: dict = None,
    ast_data: list[dict] = None,
) -> list[dict]:
    """Call all CrossFilePlugins to produce cross-file edges.

    Args:
        subgraphs: Dict of subgraph_name -> (nodes, edges)
        all_symbols: Flat list of all symbols across subgraphs
        merged_elements: Merged element dict from all subgraphs (from _reconstruct_elements)
        ast_data: AST data for plugins that need it (e.g., for parsing annotations)

    Returns:
        List of cross-file edge dicts
    """
    all_edges: list[dict] = []
    if merged_elements is None:
        merged_elements = {"templates": []}

    registry_cls = _load_cross_file_plugins()
    if registry_cls is None:
        return all_edges

    try:
        plugins = []
        for name in registry_cls.available_plugins():
            plugin = registry_cls.get(name)
            if plugin:
                plugins.append(plugin)
    except Exception:
        return all_edges

    # Build a GraphContext with the merged symbols, edges
    all_edges_list: list[dict] = []
    for sg_name, (nodes, edges) in subgraphs.items():
        all_edges_list.extend(edges)

    from plugins.common.base import GraphContext
    context = GraphContext(
        symbols=all_symbols,
        edges=all_edges_list,
        ui_data=merged_elements,
        ast_data=ast_data if ast_data is not None else [],
    )

    for plugin in plugins:
        try:
            edges = plugin.produce(context, None, merged_elements)
            if edges:
                # Convert CrossFileEdge objects to dicts if needed
                for edge in edges:
                    if hasattr(edge, "to_dict"):
                        edge = edge.to_dict()
                    all_edges.append(edge)
        except Exception as e:
            import warnings
            warnings.warn(f"CrossFilePlugin {plugin.name} failed: {e}")

    return all_edges


# ── Deduplication ─────────────────────────────────────────────────────────────

def deduplicate_cross_file_edges(edges: list[dict]) -> list[dict]:
    """Remove duplicate cross-file edges based on kind, from, and to identifiers.

    Supports both field naming conventions:
    - from_qname/to_qname (used by cross-file plugins like jsp_java)
    - from_node/to_node (used by make_cross_file_edge)
    """
    seen: set[tuple] = set()
    unique: list[dict] = []

    for edge in edges:
        # Normalize field names: support both qname and node variants
        from_id = edge.get("from_qname") or edge.get("from_node", "")
        to_id = edge.get("to_qname") or edge.get("to_node", "")
        key = (edge.get("kind"), from_id, to_id)
        if key not in seen:
            seen.add(key)
            unique.append(edge)

    return unique


def classify_edge_category(from_layer: str, to_layer: str, from_type: str, to_type: str) -> str:
    """Classify an edge into one of three categories:
    
    - intra_type: Same file type (e.g., Java→Java, JSP→JSP)
    - cross_type: Different file types, same layer (e.g., Java→XML in source layer)
    - cross_layer: Different layers (always cross-type, e.g., Java→JSP)
    
    Args:
        from_layer: Layer of source (e.g., "01_source", "02_template")
        to_layer: Layer of target
        from_type: File type of source (e.g., "java", "jsp")
        to_type: File type of target
    
    Returns:
        Edge category: "intra_type", "cross_type", or "cross_layer"
    """
    # Check layer relation first
    if from_layer != to_layer:
        return CrossFileEdgeCategory.CROSS_LAYER_EDGE
    
    # Same layer - check type relation
    if from_type == to_type:
        return CrossFileEdgeCategory.INTRA_TYPE_EDGE
    else:
        return CrossFileEdgeCategory.CROSS_TYPE_EDGE


# ── Total graph building ──────────────────────────────────────────────────────

def build_total_graph(
    subgraphs: dict[str, tuple[list[dict], list[dict]]],
    cross_file_edges: list[dict],
    *,
    filtered_subgraphs: Optional[dict[str, tuple[list[dict], list[dict]]]] = None,
) -> dict:
    """Merge all subgraphs and cross-file edges into the master graph.

    Args:
        subgraphs: Dict of subgraph_name -> (nodes, edges)
        cross_file_edges: Pre-classified cross-file edge dicts (from _classify_merged_edge
                     and CrossFilePlugins). Each must have a "category" field:
                     "intra_type", "cross_type", or "cross_layer".
        filtered_subgraphs: Optional override — if provided, use these (filtered) nodes/edges
                     instead of the unfiltered subgraphs. This enables post-pruning the
                     merged graph with cross-file edges before writing to disk.

    Returns:
        Master graph dict with nodes, edges, cross_file_edges, metadata
    """
    # Use filtered subgraphs if provided (e.g., after merged-level reachability pruning)
    use_subgraphs = filtered_subgraphs if filtered_subgraphs is not None else subgraphs

    all_nodes: list[dict] = []
    all_edges: list[dict] = []
    layer_counts: dict[str, dict] = {}

    for subgraph_name, (nodes, edges) in use_subgraphs.items():
        all_nodes.extend(nodes)
        all_edges.extend(edges)
        layer_counts[subgraph_name] = {
            "nodes": len(nodes),
            "edges": len(edges),
        }

    # Edges are already classified by category — just separate them
    intra_type: list[dict] = []
    cross_type: list[dict] = []
    cross_layer: list[dict] = []
    for edge in cross_file_edges:
        category = edge.get("category", "")
        if category == "cross_layer":
            cross_layer.append(edge)
        elif category == "cross_type":
            cross_type.append(edge)
        else:
            intra_type.append(edge)

    return {
        "nodes": all_nodes,
        "edges": all_edges,
        "cross_file_edges": cross_file_edges,
        "intra_type_cross_file_edges": intra_type,
        "cross_type_cross_file_edges": cross_type,
        "cross_layer_cross_file_edges": cross_layer,
        "metadata": {
            "total_nodes": len(all_nodes),
            "total_edges": len(all_edges),
            "total_cross_file_edges": len(cross_file_edges),
            "intra_type_count": len(intra_type),
            "cross_type_count": len(cross_type),
            "cross_layer_count": len(cross_layer),
            "subgraph_counts": layer_counts,
        },
    }


# ── Stage 6 main function ─────────────────────────────────────────────────────

def generate_cross_file_edges(
    src_root: Path,
    out_dir: Path,
    subgraph_dirs: Optional[dict[str, Path]] = None,
) -> dict:
    """Stage 6: Generate cross-file edges and build total graph.

    This is the main entry point for Stage 6 in the --all pipeline.

    Intra-Type edges (same file type, e.g., JS→JS imports) are generated in Stage 4
    by language plugins (build_import_edges, etc.) and written to the merged edges.jsonl.
    Stage 6 reads them directly and classifies them.

    Cross-Type and Cross-Layer edges are generated by CrossFilePlugins.

    Workflow:
    1. Recursively scan for all subgraph directories
    2. Read the merged edges.jsonl from the root output directory
    3. Extract Intra-Type edges directly from the merged graph (Stage 4 origin)
    4. Call CrossFilePlugins for Cross-Type and Cross-Layer edges
    5. Combine all edges and write outputs

    Args:
        src_root: Source project root (for context)
        out_dir: Output directory containing the role architecture subdirectories
        subgraph_dirs: Optional dict of category -> Path mapping (overrides scanning)

    Returns:
        Total graph dict
    """
    print(f"Stage 6: Cross-File Edge Generation...")

    # ── Step 1: Load all subgraphs ───────────────────────────────────────────
    subgraphs: dict[str, tuple[list[dict], list[dict]]] = {}
    ui_data_by_subgraph: dict[str, dict] = {}
    all_symbols: list[dict] = []

    if subgraph_dirs:
        for category, dir_path in subgraph_dirs.items():
            if dir_path.exists():
                nodes, edges = load_subgraph(dir_path)
                if nodes or edges:
                    subgraphs[category] = (nodes, edges)
                    ui_data_by_subgraph[category] = load_elements(dir_path)
                    for node in nodes:
                        sym = _node_to_symbol(node)
                        if sym.get("qualified_name"):
                            all_symbols.append(sym)
    else:
        # Flat output structure: each type has its own subdirectory directly under out_dir/
        # e.g. output/java/nodes.jsonl, output/yaml/nodes.jsonl
        for child in sorted(out_dir.iterdir()):
            if not child.is_dir():
                continue
            nodes_file = child / "nodes.jsonl"
            if nodes_file.exists():
                category = child.name
                nodes, edges = load_subgraph(child)
                if nodes or edges:
                    subgraphs[category] = (nodes, edges)
                    ui_data_by_subgraph[category] = load_elements(child)
                    for node in nodes:
                        sym = _node_to_symbol(node)
                        if sym.get("qualified_name"):
                            all_symbols.append(sym)

    print(f"  Loaded {len(subgraphs)} subgraphs, {len(all_symbols)} total symbols")

    # ── Step 2: Extract Intra-Type edges from the merged edges.jsonl ───────────
    # Build qname -> file index from the merged nodes.jsonl (written by Stage 5).
    # Source file for each edge comes from edge["file"]; target file is resolved
    # by looking up edge["to_qname"] in the qname index.
    qname_to_file: dict[str, str] = {}
    merged_nodes_file = out_dir / "nodes.jsonl"
    for node in _load_jsonl(merged_nodes_file):
        qn = node.get("qualified_name") or node.get("id", "")
        f = node.get("file", "")
        if qn and f:
            qname_to_file[qn] = f

    merged_edges_file = out_dir / "edges.jsonl"
    merged_edges: list[dict] = _load_jsonl(merged_edges_file)

    seen_intra: set[tuple] = set()
    intra_type_edges: list[dict] = []
    for edge in merged_edges:
        classified = _classify_merged_edge(edge, qname_to_file)
        if classified:
            key = (classified["from_qname"], classified["to_qname"], classified["kind"])
            if key not in seen_intra:
                seen_intra.add(key)
                intra_type_edges.append(classified)

    print(f"  Intra-Type edges (from Stage 4): {len(intra_type_edges)}")

    # ── Step 3: CrossFilePlugins generate Cross-Type and Cross-Layer edges ─────
    merged_elements: dict = {"templates": []}
    for sg_elements in ui_data_by_subgraph.values():
        for key, value in sg_elements.items():
            if key == "templates":
                merged_elements.setdefault(key, []).extend(value or [])
            else:
                merged_elements.setdefault(key, []).extend(value if isinstance(value, list) else [])

    plugin_edges = produce_cross_file_edges(subgraphs, all_symbols, merged_elements, ast_data=None)
    plugin_edges = deduplicate_cross_file_edges(plugin_edges)

    # Classify plugin edges (Cross-Type or Cross-Layer)
    # Build qname -> file mapping from symbols for edge classification
    qname_to_sym_file: dict[str, str] = {}
    for sym in all_symbols:
        qn = sym.get("qualified_name", "")
        f = sym.get("file", "")
        if qn and f:
            qname_to_sym_file[qn] = f

    cross_type_edges: list[dict] = []
    cross_layer_edges: list[dict] = []
    for edge in plugin_edges:
        from_qname = edge.get("from_qname", "")
        to_qname = edge.get("to_qname", "")

        # Resolve files: explicit field > symbol qname mapping > qname prefix extraction
        from_file = edge.get("from_file", "") or qname_to_sym_file.get(from_qname, "") or _extract_file_from_qname(from_qname)
        to_file = edge.get("to_file", "") or qname_to_sym_file.get(to_qname, "") or _extract_file_from_qname(to_qname)

        from_layer = edge.get("from_layer", "") or get_layer_from_path(from_file)
        to_layer = edge.get("to_layer", "") or get_layer_from_path(to_file)
        from_type = edge.get("from_type", "") or get_file_type(from_file) or _infer_type_from_qname(from_qname)
        to_type = edge.get("to_type", "") or get_file_type(to_file) or _infer_type_from_qname(to_qname)
        edge["category"] = classify_edge_category(from_layer, to_layer, from_type, to_type)

        if edge["category"] == "cross_layer":
            cross_layer_edges.append(edge)
        elif edge["category"] == "cross_type":
            cross_type_edges.append(edge)

    print(f"  Cross-Type edges (from CrossFilePlugins): {len(cross_type_edges)}")
    print(f"  Cross-Layer edges (from CrossFilePlugins): {len(cross_layer_edges)}")

    # ── Step 4: Combine all cross-file edges ───────────────────────────────────
    all_cross_file_edges = intra_type_edges + cross_type_edges + cross_layer_edges
    print(f"  Total cross-file edges: {len(all_cross_file_edges)}")

    # ── Step 4b: Reachability pruning on the merged graph ──────────────────────
    # Use the FULL merged edge set (intra-type + cross-file) so that nodes reachable
    # only through cross-layer/cross-type edges are NOT incorrectly removed.
    # This is the single authoritative pruning point for the total graph.
    all_merged_edges = merged_edges + all_cross_file_edges
    filtered_symbols, filtered_edges, prune_stats = prune_disconnected_components(
        all_symbols, all_merged_edges, verbose=True
    )
    filtered_qnames: set[str] = {s["qualified_name"] for s in filtered_symbols}

    # Reconstruct filtered subgraphs — only nodes that survived pruning
    filtered_subgraphs: dict[str, tuple[list[dict], list[dict]]] = {}
    for sg_name, (nodes, edges) in subgraphs.items():
        sg_nodes = [
            n for n in nodes
            if (n.get("qualified_name") or n.get("id", "")) in filtered_qnames
        ]
        sg_edges = [
            e for e in edges
            if (e.get("from_qname", "") in filtered_qnames
                or e.get("to_qname", "") in filtered_qnames)
        ]
        if sg_nodes:
            filtered_subgraphs[sg_name] = (sg_nodes, sg_edges)

    # Collect db:: virtual node identifiers from cross-file edges so they survive pruning.
    # sql_mapping edges have to_qname like "db::article.id" which won't be in the symbol table.
    for edge in all_cross_file_edges:
        to_qn = edge.get("to_qname", "")
        from_qn = edge.get("from_qname", "")
        if to_qn.startswith("db::") or from_qn.startswith("db::"):
            if to_qn:
                filtered_qnames.add(to_qn)
            if from_qn:
                filtered_qnames.add(from_qn)

    # Keep only cross-file edges whose both endpoints survived pruning
    all_cross_file_edges = [
        e for e in all_cross_file_edges
        if (e.get("from_qname", "") in filtered_qnames
            or e.get("from_file", "") in filtered_qnames)
        and (e.get("to_qname", "") in filtered_qnames
            or e.get("to_file", "") in filtered_qnames)
    ]

    print(f"  After merged-level pruning: {len(filtered_symbols)} nodes, "
          f"{len(filtered_edges)} edges, {len(all_cross_file_edges)} cross-file edges remain")

    # ── Step 5: Build and write outputs ──────────────────────────────────────
    total_graph = build_total_graph(
        subgraphs, all_cross_file_edges, filtered_subgraphs=filtered_subgraphs
    )

    cross_edges_file = out_dir / "cross_file_edges.json"
    cross_edges_file.write_text(
        json.dumps(all_cross_file_edges, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  Written: {cross_edges_file}")

    all_graph_file = out_dir / "all_graph.json"
    all_graph_file.write_text(
        json.dumps(total_graph, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  Written: {all_graph_file}")

    # Write filtered nodes and edges back to the root directory
    # so _build_viewer reads the clean (pruned) graph
    filtered_out_nodes = total_graph["nodes"]
    filtered_out_edges = total_graph["edges"]
    (out_dir / "nodes.jsonl").write_text(
        "\n".join(json.dumps(n, ensure_ascii=False) for n in filtered_out_nodes),
        encoding="utf-8")
    (out_dir / "edges.jsonl").write_text(
        "\n".join(json.dumps(e, ensure_ascii=False) for e in filtered_out_edges),
        encoding="utf-8")
    print(f"  Written: nodes.jsonl ({len(filtered_out_nodes)}), edges.jsonl ({len(filtered_out_edges)})")

    return total_graph


def generate_cross_file_edges_for_type(
    src_root: Path,
    out_dir: Path,
    file_type: str,
) -> dict:
    """Generate cross-file edges for a specific file type (--singlefile mode).

    This variant:
    - Loads only subgraphs related to the specified type
    - Generates cross-file edges involving that type
    - Writes the subgraph + related cross-file edges (not the full master graph)

    Args:
        src_root: Source project root
        out_dir: Output directory
        file_type: File type code (e.g., "java", "jsp", "yaml")

    Returns:
        Dict with subgraph data and related cross-file edges
    """
    print(f"Stage 6: Cross-File Edge Generation for type: {file_type}")

    from classify import get_role_for_file_type

    target_role = get_role_for_file_type(file_type)
    if target_role is None:
        print(f"  Unknown file type: {file_type}, skipping cross-file edge generation")
        return {"nodes": [], "edges": [], "cross_file_edges": []}

    layer, subcat = target_role
    category = f"{layer}/{subcat}"

    # Load the target subgraph (flat: output/{type}/)
    target_dir = out_dir / file_type
    target_nodes, target_edges = load_subgraph(target_dir)

    # Find related subgraphs in the flat output directory
    subgraphs: dict[str, tuple[list[dict], list[dict]]] = {category: (target_nodes, target_edges)}
    ui_data_by_subgraph: dict[str, dict] = {category: _reconstruct_elements(target_nodes)}
    all_symbols: list[dict] = [_node_to_symbol(n) for n in target_nodes if _node_to_symbol(n).get("qualified_name")]

    # Scan for related subgraphs (all type directories in flat output)
    for subdir in sorted(out_dir.iterdir()):
        if not subdir.is_dir() or subdir.name == file_type:
            continue
        # Load related subgraph for cross-edge detection
        nodes, edges = load_subgraph(subdir)
        if nodes:
            related_category = subdir.name
            subgraphs[related_category] = (nodes, edges)
            ui_data_by_subgraph[related_category] = load_elements(subdir)
            all_symbols.extend(_node_to_symbol(n) for n in nodes if _node_to_symbol(n).get("qualified_name"))

    print(f"  Loaded {len(subgraphs)} related subgraphs for {file_type}")

    # Merge elements from all subgraphs into one dict for cross-file plugins
    merged_elements: dict = {"templates": []}
    for sg_elements in ui_data_by_subgraph.values():
        for key, value in sg_elements.items():
            if key == "templates":
                merged_elements.setdefault(key, []).extend(value or [])
            else:
                merged_elements.setdefault(key, []).extend(value if isinstance(value, list) else [])

    # Produce cross-file edges
    cross_edges = produce_cross_file_edges(subgraphs, all_symbols, merged_elements, ast_data=None)

    # Deduplicate first (normalize from_qname/to_qname vs from_node/to_node)
    cross_edges = deduplicate_cross_file_edges(cross_edges)

    # Classify edges by layer
    for edge in cross_edges:
        from_layer = edge.get("from_layer", "")
        to_layer = edge.get("to_layer", "")
        edge["category"] = classify_edge_category(from_layer, to_layer)

    # Filter to only edges involving the target type
    target_cross_edges = [
        e for e in cross_edges
        if file_type in e.get("from_file", "") or file_type in e.get("to_file", "")
        or category in [e.get("from_layer"), e.get("to_layer")]
    ]

    print(f"  Generated {len(target_cross_edges)} cross-file edges for {file_type}")

    # Write output
    result = {
        "nodes": target_nodes,
        "edges": target_edges,
        "cross_file_edges": target_cross_edges,
        "metadata": {
            "file_type": file_type,
            "role": category,
            "total_nodes": len(target_nodes),
            "total_edges": len(target_edges),
            "related_cross_edges": len(target_cross_edges),
        },
    }

    cross_edges_file = out_dir / file_type / "cross_file_edges.json"
    cross_edges_file.parent.mkdir(parents=True, exist_ok=True)
    cross_edges_file.write_text(
        json.dumps(target_cross_edges, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  Written: {cross_edges_file}")

    return result
