"""Edge quality evaluation, tier classification, and graph pruning utilities.

This module provides shared infrastructure for the plugin system to:
- Evaluate whether an edge is worth keeping in the graph
- Classify edges into semantic tiers (core / ui / config / template)
- Prune disconnected components that are not reachable from entry points
- Filter noise edges generated by plugins

Design principle: plugin-generated edges are assumed to be noisy unless proven
otherwise. An edge is only kept if at least one endpoint belongs to the main
code cluster (a resolved symbol, a UI file node, or a config file node).
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional
from tqdm import tqdm

from plugins.common.base import GraphContext


# ── Edge tier definitions ────────────────────────────────────────────────────

TIER_CORE = "core"
TIER_UI = "ui"
TIER_CONFIG = "config"
TIER_BUILD = "build"
TIER_TEMPLATE = "template"
TIER_MISC = "misc"

# Kind → tier mapping. Unknown kinds default to TIER_MISC (kept but deprioritized).
KIND_TO_TIER: dict[str, str] = {
    # Core semantic edges
    "call": TIER_CORE,
    "contains": TIER_CORE,
    "extends": TIER_CORE,
    "implements": TIER_CORE,
    "instantiates": TIER_CORE,
    "imports": TIER_CORE,
    "defined_in": TIER_CORE,
    "inner_class": TIER_CORE,
    # reads/writes are treated as core but may be filtered by reads_writes_mode
    "reads": TIER_CORE,
    "writes": TIER_CORE,
    # Generic typed_as/returns
    "typed_as": TIER_CORE,
    "returns": TIER_CORE,
    # Java-specific extends/implements (from JavaPlugin)
    "java_extends": TIER_CORE,
    "java_implements": TIER_CORE,
    # Template include (treated as core-level for template structure)
    "template_include": TIER_CORE,
    "template_url_for": TIER_CORE,
    # Render edges
    "renders": TIER_CORE,
    "bound_to": TIER_CORE,
    # Call-graph helper edges
    "cross_call": TIER_CORE,

    # SQL/ORM field mapping edges
    "sql_mapping": TIER_CORE,

    # UI-layer edges
    "jsp_entry": TIER_UI,
    "jsp_form_submit": TIER_UI,
    "execute_return": TIER_UI,
    "action_route": TIER_UI,
    "forward_route": TIER_UI,
    "form_bound": TIER_UI,
    "di_bound": TIER_UI,
    "di_component": TIER_UI,
    "servlet_bound": TIER_UI,
    "filter_chain": TIER_UI,
    "uses_tag": TIER_UI,
    "template_ref": TIER_UI,

    # Config-layer edges
    "config.bean": TIER_CONFIG,
    "config.class": TIER_CONFIG,
    "config.url": TIER_CONFIG,
    "config.env_var": TIER_CONFIG,
    "config.export": TIER_CONFIG,
    "config.package": TIER_CONFIG,
    # Generic config.* (fallback)
    "config.import": TIER_CONFIG,
    "config.ref": TIER_CONFIG,

    # Build-layer edges (deprecated — build deps are not part of the business impact chain)
    # Removed: test.dep, maven.dep, gradle.dep, npm.dep, pip.dep, go.dep

    # Template-layer edges
    "template_to_symbol": TIER_TEMPLATE,
    "template_to_file": TIER_TEMPLATE,
    "template_to_url": TIER_TEMPLATE,
}

# Prefixes that indicate a qname is NOT part of the main code cluster
_NON_CLUSTER_PREFIXES = (
    "ext::",
    "config::",
    "tag::",
    "forward::",
    "url::",
    "pattern::",
    "servlet::",
    "filter::",
    "formbean::",
    "ctxparam::",
    "package::",
    "file::",      # file nodes are cluster-adjacent but not code symbols
)


# ── Dataclasses ──────────────────────────────────────────────────────────────


@dataclass
class EdgeQualityResult:
    """Result of evaluating a single edge."""
    keep: bool
    reason: str
    tier: str = TIER_MISC


@dataclass
class PluginContributionLimits:
    """Per-plugin contribution caps to prevent noise explosions.

    These limits are enforced at the plugin call site (stage4_refs.py) so
    plugins cannot unilaterally bloat the graph.
    """
    max_nodes: int = 0       # 0 = no limit
    max_edges: int = 200     # per file / per plugin call
    max_edges_global: int = 2000  # total across all calls
    require_cluster_link: bool = True   # at least one endpoint in main cluster
    skip_on_no_symbols: bool = True     # skip if no project symbols exist
    min_confidence: str = "low"  # "high" | "medium" | "low"


@dataclass
class PruneStats:
    """Statistics from a reachability prune pass."""
    original_nodes: int
    original_edges: int
    kept_nodes: int
    kept_edges: int
    entry_points: int = 0
    removed_tiers: dict[str, int] = field(default_factory=dict)


# ── Core cluster detection ────────────────────────────────────────────────────


def is_in_main_cluster(qname: str) -> bool:
    """Return True if qname belongs to the main code cluster.

    The main cluster consists of:
    - Project symbols (class/interface/method/field names parsed from source)
    - UI file nodes (file::<path>)
    - Config file nodes (config::<path>)
    - Virtual structural nodes (tag::, forward::, url::, etc.)
    - Any qname that looks like a resolvable code path

    NOT in the main cluster:
    - ext::* external stub references
    - Bare module names like "requests", "numpy", "react"
    - Anonymous or generated identifiers
    """
    if not qname:
        return False
    for prefix in _NON_CLUSTER_PREFIXES:
        if qname.startswith(prefix):
            return False
    if looks_like_external_module(qname):
        return False
    return True


def is_cluster_adjacent(qname: str) -> bool:
    """Return True if qname is adjacent to the cluster (file/config/UI nodes).

    These nodes are not code symbols but serve as important structural anchors.
    """
    return qname.startswith("file::") or qname.startswith("config::")


def looks_like_external_module(name: str) -> bool:
    """Heuristic: does this look like a bare third-party module/package name?

    Examples that return True:
        "requests", "numpy", "react", "lodash", "express", "flask"
        "io.netty", "org.apache.commons", "com.google.guava"

    Examples that return False:
        "jp.co.rct.myapp.service.UserService"  (project code)
        "java.util.List"                        (stdlib, also treated as external)
        "file::src/main/java/Foo.java"          (file node)
    """
    if not name:
        return False
    if "/" in name or "\\" in name:
        return False

    parts = name.split(".")

    # Single-segment names are almost always external modules
    if len(parts) == 1:
        # Exclude things that look like class/interface names (PascalCase)
        if parts[0] and parts[0][0].isupper():
            return False
        return True

    # Two-segment names: could be "pkg.Class" (project) or "org.X" (external)
    if len(parts) == 2:
        # Heuristic: common external package roots
        common_ext = (
            "requests", "numpy", "pandas", "flask", "django", "fastapi",
            "express", "react", "vue", "angular", "next", "lodash",
            "pip", "npm", "go", "java", "javax", "io", "org", "com",
            "org.springframework", "org.apache", "org.hibernate",
            "com.google", "ch.qos",
        )
        root = parts[0]
        if root in common_ext:
            return True
        # Otherwise treat as project code
        return False

    # Three or more segments: likely "org.pkg.name" style external packages
    root = parts[0]
    common_ext_roots = (
        "org", "com", "io", "cn", "net", "gov", "edu",
        "requests", "numpy", "pandas", "pip", "npm", "go",
    )
    if root in common_ext_roots:
        # But exclude if it looks like a project (non-standard TLDs)
        # Most projects use com.company.project or org.framework patterns
        if len(parts) >= 3:
            second = parts[1]
            # Exclude common corporate/project patterns
            if second in ("company", "corp", "main", "core", "common",
                          "internal", "base", "util", "shared"):
                return False
        return True

    return False


# ── Edge evaluation ───────────────────────────────────────────────────────────


def evaluate_edge(edge: dict) -> EdgeQualityResult:
    """Determine whether an edge should be kept in the final graph.

    Decision strategy:
    - Core semantic edges (call/extends/implements/etc.) are always kept
    - Edges where neither endpoint is in the cluster are dropped
    - Config import edges to bare external modules are dropped
    - Template edges without cluster connectivity are dropped
    - External type refs (ext::) for typed_as/returns are kept (useful for IDE)
    - All other edges are kept by default
    """
    kind = edge.get("kind", "")
    from_qn = edge.get("from_qname", "")
    to_qn = edge.get("to_qname", "")
    from_in = is_in_main_cluster(from_qn)
    to_in = is_in_main_cluster(to_qn)
    from_adj = is_cluster_adjacent(from_qn)
    to_adj = is_cluster_adjacent(to_qn)

    # Core semantic edges — always keep
    if kind in (
        "call", "contains", "extends", "implements", "instantiates",
        "imports", "defined_in", "reads", "writes", "renders",
        "cross_call", "bound_to", "inner_class", "sql_mapping",
    ):
        return EdgeQualityResult(True, "core_semantic", KIND_TO_TIER.get(kind, TIER_CORE))

    # UI-layer edges — always keep
    if kind in (
        "jsp_entry", "jsp_form_submit", "execute_return", "action_route",
        "forward_route", "form_bound", "di_bound", "di_component",
        "servlet_bound", "filter_chain", "uses_tag",
    ):
        return EdgeQualityResult(True, "ui_layer", KIND_TO_TIER.get(kind, TIER_UI))

    # typed_as / returns — keep if either endpoint is in cluster or is ext::
    if kind in ("typed_as", "returns"):
        if to_qn.startswith("ext::") or from_qn.startswith("ext::"):
            return EdgeQualityResult(True, "external_type_ref", TIER_CORE)
        if from_in or to_in:
            return EdgeQualityResult(True, "internal_type_ref", TIER_CORE)
        # Neither endpoint in cluster
        return EdgeQualityResult(False, "orphan_type_ref", TIER_MISC)

    # Build dependency edges — keep (will be migrated to node attrs in Phase 4)
    if kind.endswith(".dep"):
        tier = KIND_TO_TIER.get(kind, TIER_BUILD)
        return EdgeQualityResult(True, "build_dep", tier)

    # Config edges
    if kind.startswith("config."):
        # config.export: config file → project symbol (meaningful)
        if kind == "config.export" and to_in:
            return EdgeQualityResult(True, "config_export", TIER_CONFIG)
        # config.bean: bean reference to class (meaningful)
        if kind == "config.bean" and to_in:
            return EdgeQualityResult(True, "config_bean", TIER_CONFIG)
        # config.import: config file → bare external module name (noise)
        if kind == "config.import":
            return EdgeQualityResult(False, "external_module_ref", TIER_MISC)
        # config.class / config.url / config.env_var — keep if connects to cluster
        if (from_in or from_adj) and (to_in or to_adj):
            return EdgeQualityResult(True, "config_clustered", TIER_CONFIG)
        # Otherwise: at least one side is cluster-adjacent
        if from_in or from_adj or to_in or to_adj:
            return EdgeQualityResult(True, "config_partial", TIER_CONFIG)
        return EdgeQualityResult(False, "orphan_config", TIER_MISC)

    # Template edges
    if kind in ("template_to_symbol", "template_ref", "template_include",
                "template_url_for", "template_to_file", "template_to_url"):
        # Must connect to the main cluster
        if (from_in or from_adj) and (to_in or to_adj):
            return EdgeQualityResult(True, "template_clustered", TIER_TEMPLATE)
        if to_in and not from_in and not from_adj:
            return EdgeQualityResult(False, "orphan_template_to_code", TIER_MISC)
        return EdgeQualityResult(False, "orphan_template", TIER_MISC)

    # Generic fallback: keep if at least one endpoint is in/adjacent to cluster
    if from_in or to_in or from_adj or to_adj:
        return EdgeQualityResult(True, "fallback_clustered", TIER_MISC)

    return EdgeQualityResult(False, "fully_orphan", TIER_MISC)


def filter_edges(edges: list[dict], *, max_edges_global: int = 0) -> list[dict]:
    """Apply quality filter to a list of edges.

    Args:
        edges: List of edge dicts
        max_edges_global: If > 0, cap total output to this many edges (deduplicated)

    Returns:
        Filtered list of edges
    """
    result = []
    for edge in edges:
        r = evaluate_edge(edge)
        if r.keep:
            result.append(edge)

    if max_edges_global > 0 and len(result) > max_edges_global:
        result = _dedup_and_truncate(result, max_edges_global)

    return result


def _dedup_and_truncate(edges: list[dict], limit: int) -> list[dict]:
    """Deduplicate edges by (kind, from_qname, to_qname) then truncate."""
    seen: set[tuple] = set()
    deduped: list[dict] = []
    for e in edges:
        key = (e.get("kind"), e.get("from_qname"), e.get("to_qname"))
        if key not in seen:
            seen.add(key)
            deduped.append(e)
    return deduped[:limit]


# ── Reachability pruning ──────────────────────────────────────────────────────


# Domain tags that mark a symbol as a graph entry point.
# These are the TRUE anchors of the graph — the symbols that represent
# application entry points (HTTP handlers, test cases, etc.).
_ENTRY_TAGS: frozenset[str] = frozenset({
    # Java / JVM
    "struts.action",
    "spring.get_mapping",
    "spring.post_mapping",
    "spring.put_mapping",
    "spring.delete_mapping",
    "spring.mapping",
    "spring.rest_controller",
    "spring.controller",
    "jpa.entity",
    "test.case",
    "test.integration",
    "test.web",
    "test.fixture",
    "test.parametrized",
    # Python web frameworks
    "web.route",
    "fastapi.route",
    "test.pytest.fixture",
    # JavaScript / TypeScript
    "react.component",
    "angular.module",
})

# Edge kinds that mark a target symbol as an entry point.
# NOTE: "defined_in" is deliberately excluded — every symbol has a defined_in edge
# to its file node, so including it would make every symbol an entry point and
# defeat the entire purpose of reachability pruning.
_ENTRY_EDGE_KINDS: frozenset[str] = frozenset({
    # UI / web-layer references
    "execute_return", "jsp_entry", "jsp_form_submit",
    "action_route", "forward_route", "form_bound",
    "di_bound", "di_component", "servlet_bound",
    "template_to_symbol", "template_include",
    "uses_tag", "template_ref", "template_url_for",
    "renders",
})


def collect_entry_points(symbols: list[dict], edges: list[dict]) -> set[str]:
    """Collect all qualified names that are considered graph entry points.

    Entry points are:
    1. Symbols with entry-point domain tags
    2. Symbols referenced by UI-layer edges
    3. Symbols that are called by other symbols (call-graph reverse traversal)
    4. Naming-convention entry points for Python web frameworks
    5. Framework-specific entry point detection via FrameworkPlugin.detect_entry_points()
    """
    entries: set[str] = set()

    # 1. Tag-based entry points
    for sym in symbols:
        for tag in sym.get("domain_tags", []):
            if tag in _ENTRY_TAGS:
                entries.add(sym["qualified_name"])
                break

    # 2. UI-edge-referenced symbols
    for edge in edges:
        kind = edge.get("kind", "")
        if kind not in _ENTRY_EDGE_KINDS:
            continue
        to_qn = edge.get("to_qname", "")
        if to_qn and not to_qn.startswith("ext::"):
            entries.add(to_qn)
        from_qn = edge.get("from_qname", "")
        if from_qn and not from_qn.startswith("ext::"):
            entries.add(from_qn)

    # 3. Called symbols as implicit entry points (call-graph seeds)
    # If symbol B is called by symbol A, B is reachable from an entry point.
    for edge in edges:
        if edge.get("kind") == "call":
            to_qn = edge.get("to_qname", "")
            from_qn = edge.get("from_qname", "")
            if to_qn and not to_qn.startswith("ext::"):
                entries.add(to_qn)
            if from_qn and not from_qn.startswith("ext::"):
                entries.add(from_qn)

    # 4. Naming-convention entry points for Python web frameworks
    _PYTHON_WEB_NAMES = frozenset({
        "main", "app", "serve", "run", "create_app",
        "make_app", "init_app", "application", "asgi", "wsgi",
    })
    _PYTHON_WEB_FILES = frozenset({
        "app.py", "main.py", "application.py", "__init__.py",
        "asgi.py", "wsgi.py", "run.py", "server.py",
    })
    for sym in symbols:
        kind = sym.get("kind", "")
        if kind not in ("function", "method"):
            continue
        name = sym.get("name", "")
        qname = sym.get("qualified_name", "")
        file_path = sym.get("file", "")
        file_name = Path(file_path).name if file_path else ""

        # Named entry points
        if name in _PYTHON_WEB_NAMES:
            entries.add(qname)

        # app.py / main.py / etc. with top-level function
        if file_name in _PYTHON_WEB_FILES and name != "<lambda>":
            entries.add(qname)

        # __init__.py that exports a Flask/FastAPI app instance
        if file_name == "__init__.py":
            if "app" in name.lower() or "application" in name.lower():
                entries.add(qname)

    # 5. Framework-plugin entry point detection
    # Delegates to FastAPI, Flask, Spring, etc. for framework-specific patterns
    try:
        from .plugins.cfg_03_config.framework import FrameworkRegistry
    except ImportError:
        try:
            from plugins.cfg_03_config.framework import FrameworkRegistry
        except ImportError:
            FrameworkRegistry = None

    if FrameworkRegistry is not None:
        # Infer language from symbols
        lang = "java"
        for sym in symbols:
            l = sym.get("lang", "")
            if l and l != "unknown":
                lang = l
                break

        context = GraphContext(symbols=symbols, edges=edges)
        for fw_plugin in FrameworkRegistry.get_for_lang(lang):
            try:
                detected = fw_plugin.detect_entry_points(context)
                for qn in detected:
                    if qn and not qn.startswith("ext::"):
                        entries.add(qn)
            except Exception:
                pass

    return entries


def prune_disconnected_components(
    symbols: list[dict],
    edges: list[dict],
    *,
    verbose: bool = True,
) -> tuple[list[dict], list[dict], PruneStats]:
    """Remove nodes and edges that are not reachable from any entry point.

    Entry point sources:
    1. Symbols with entry-point domain tags
    2. Symbols referenced by UI-layer edges
    3. Naming-convention entry points (main/app/serve for Python web, etc.)
    4. Symbols that are call-graph seeds (from_qname of "call" edges)

    Traversal rules:
    - FOLLOW call edges (both directions): symbol A calls B → reachable both ways
    - FOLLOW defined_in edges only FROM symbol TO file (forward only):
      file → symbol paths are NOT traversed (would make all symbols in a file reachable)

    Result: Only the call graph cluster containing the entry points is kept.
    Orphaned symbols (even if they share a file with entry points) are removed.
    """
    entries = collect_entry_points(symbols, edges)

    if not entries:
        stats = PruneStats(
            original_nodes=len(symbols),
            original_edges=len(edges),
            kept_nodes=len(symbols),
            kept_edges=len(edges),
            entry_points=0,
        )
        return symbols, edges, stats

    # BFS: selectively follow edges to find all reachable nodes
    reachable: set[str] = set(entries)
    # adjacency: symbol → list of (neighbor, allow_reverse)
    adj: dict[str, list[tuple[str, bool]]] = {}
    for e in tqdm(edges, desc="  Stage 5a build adj", unit="edge", ncols=80, leave=False):
        fr = e.get("from_qname", "")
        to = e.get("to_qname", "")
        if not fr or not to:
            continue
        kind = e.get("kind", "")
        if kind == "call":
            # Call edges: bidirectional (A calls B means A→B and B→A both reachable)
            adj.setdefault(fr, []).append((to, True))
            adj.setdefault(to, []).append((fr, True))
        elif kind == "defined_in":
            # defined_in: symbol → file only (forward only)
            # Do NOT traverse file → symbol (would make all symbols in a file reachable)
            adj.setdefault(fr, []).append((to, False))
        elif kind in (
            "extends", "implements", "instantiates", "imports",
            "typed_as", "returns", "contains",
            "renders", "reads", "writes", "inner_class",
            "sql_mapping",
        ):
            # Structural edges: bidirectional within the code cluster
            adj.setdefault(fr, []).append((to, True))
            adj.setdefault(to, []).append((fr, True))

    queue = list(entries)
    with tqdm(desc="  Stage 5b BFS", unit="node", ncols=80, leave=False) as bar:
        while queue:
            curr = queue.pop()
            bar.update(1)
            for nb, allow_reverse in adj.get(curr, []):
                if nb not in reachable:
                    reachable.add(nb)
                    queue.append(nb)

    kept_symbols = [s for s in symbols if s["qualified_name"] in reachable]
    kept_edges = [
        e for e in edges
        if (e.get("from_qname", "") in reachable
            or e.get("to_qname", "") in reachable)
    ]

    # Tier breakdown of removed edges
    removed_by_tier: dict[str, int] = {}
    removed_qnames = {s["qualified_name"] for s in symbols} - reachable
    for e in edges:
        if e.get("from_qname", "") in removed_qnames or e.get("to_qname", "") in removed_qnames:
            tier = KIND_TO_TIER.get(e.get("kind", ""), TIER_MISC)
            removed_by_tier[tier] = removed_by_tier.get(tier, 0) + 1

    stats = PruneStats(
        original_nodes=len(symbols),
        original_edges=len(edges),
        kept_nodes=len(kept_symbols),
        kept_edges=len(kept_edges),
        entry_points=len(entries),
        removed_tiers=removed_by_tier,
    )

    if verbose:
        removed_nodes = len(symbols) - len(kept_symbols)
        removed_edges = len(edges) - len(kept_edges)
        print(f"  reachability prune: {removed_nodes} nodes, {removed_edges} edges removed")
        print(f"    ({len(kept_symbols)} nodes remain, {len(entries)} entry points)")

    return kept_symbols, kept_edges, stats


def report_disconnected_components(
    original_symbols: list[dict],
    kept_qnames: set[str],
) -> None:
    """Print a human-readable report of what was removed by pruning.

    This is informational only — it does not affect the graph.
    """
    removed = [
        s for s in original_symbols
        if s["qualified_name"] not in kept_qnames
    ]
    if not removed:
        return

    by_file: dict[str, list[dict]] = {}
    for s in removed:
        by_file.setdefault(s.get("file", "unknown"), []).append(s)

    print("\n  [Disconnected components pruned]")
    for file_path, syms in sorted(by_file.items(), key=lambda x: -len(x[1]))[:10]:
        kinds: dict[str, int] = {}
        for s in syms:
            k = s.get("kind", "unknown")
            kinds[k] = kinds.get(k, 0) + 1
        print(f"    {file_path}: {len(syms)} symbols — {dict(sorted(kinds.items(), key=lambda x: -x[1])[:3])}")


# ── Per-plugin contribution limits ──────────────────────────────────────────


def apply_plugin_limits(
    edges: list[dict],
    limits: PluginContributionLimits,
    *,
    file_key: str = "",
    global_count: int = 0,
) -> tuple[list[dict], int]:
    """Apply PluginContributionLimits to a list of edges.

    Returns (filtered_edges, dropped_count).
    """
    if not edges:
        return edges, 0

    original = len(edges)

    # Global cap
    if limits.max_edges_global and global_count >= limits.max_edges_global:
        return [], original

    # Per-call cap with deduplication
    if limits.max_edges and len(edges) > limits.max_edges:
        edges = _dedup_and_truncate(edges, limits.max_edges)

    # Cluster-link filter
    if limits.require_cluster_link:
        edges = [e for e in edges if evaluate_edge(e).keep]

    dropped = original - len(edges)
    return edges, dropped


# ── High-level pipeline functions ─────────────────────────────────────────────


def clean_graph(
    symbols: list[dict],
    edges: list[dict],
    *,
    prune: bool = True,
    max_edges_global: int = 50000,
    verbose: bool = True,
) -> tuple[list[dict], list[dict], PruneStats]:
    """Run the full edge quality pipeline.

    Applies in order:
    1. Quality filter (drop fully orphan edges)
    2. Optional reachability pruning (drop disconnected components)
    3. Global cap with deduplication

    Args:
        symbols: Symbol list
        edges: Edge list
        prune: Whether to run reachability pruning
        max_edges_global: Hard cap on total edges (0 = no cap)
        verbose: Print stats

    Returns:
        (cleaned_symbols, cleaned_edges, stats)
    """
    if verbose:
        print(f"  clean_graph: {len(symbols)} nodes, {len(edges)} edges in")

    # 1. Quality filter
    edges = filter_edges(edges, max_edges_global=max_edges_global)
    if verbose:
        print(f"    quality filter: {len(edges)} edges remain")

    # 2. Reachability pruning
    if prune:
        symbols, edges, stats = prune_disconnected_components(
            symbols, edges, verbose=verbose
        )
    else:
        stats = PruneStats(
            original_nodes=len(symbols),
            original_edges=len(edges),
            kept_nodes=len(symbols),
            kept_edges=len(edges),
            entry_points=0,
        )

    # 3. Global cap (already applied in step 1 if max_edges_global > 0)
    if verbose:
        print(f"  clean_graph out: {len(symbols)} nodes, {len(edges)} edges")

    return symbols, edges, stats
