"""Run the full 5-stage pipeline and produce a knowledge graph JSON.

Supports multiple languages via plugins (Python, JavaScript/TypeScript, Go, Java, and C/C++).
"""

import json
import os
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional, Literal
from pathlib import Path
from tqdm import tqdm

# Locate the scripts project root (this file's parent directory).
_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR
if (_PROJECT_ROOT / "stage1_syntax.py").exists():
    sys.path.insert(0, str(_PROJECT_ROOT))
elif (_SCRIPT_DIR.parent / "stage1_syntax.py").exists():
    _PROJECT_ROOT = _SCRIPT_DIR.parent
    sys.path.insert(0, str(_PROJECT_ROOT))

from stage1_syntax import parse_directory
from stage2_symbols import build_symbol_table
from stage3_types import infer_types
from stage4_refs import resolve_references
from stage5_semantic import semantic_enrichment
from stage0_classify import (
    classify_project_files,
    classify_file,
    build_output_structure,
    classify_to_output_dir,
    print_classification_summary,
    get_role_for_file_type,
    LAYER_METADATA,
    FILE_TYPE_CODE_MAP,
)
from stage6_cross_file import (
    generate_cross_file_edges,
    generate_cross_file_edges_for_type,
    CROSS_FILE_EDGE_DESCRIPTIONS,
)
from _build_viewer import main as _build_viewer
from edge_quality import (
    KIND_TO_TIER,
    TIER_CORE, TIER_UI, TIER_CONFIG, TIER_BUILD, TIER_TEMPLATE,
    is_in_main_cluster, is_cluster_adjacent,
    collect_entry_points, prune_disconnected_components,
    report_disconnected_components,
)


# ══════════════════════════════════════════════════════════════════════════════
#  Unified File Type System
# ══════════════════════════════════════════════════════════════════════════════
#  Design principle: all file types (source code, templates, configs) are
#  first-class citizens. Each FileTypeHandler produces:
#    1. parse()        → raw parse results (AST / elements / entries)
#    2. build_subgraph() → nodes + intra-type edges
#    3. write_jsonl()    → nodes.jsonl + edges.jsonl
#  The three-stage subgraph pipeline is shared for ALL types.

FileType = Literal[
    "java", "python", "javascript", "go", "cpp",
    "jsp", "jinja2", "react", "vue", "go_template", "html_template",
    "yaml", "json", "properties", "env",
    "tld", "struts_config", "web_xml", "dicon",
]


@dataclass
class ParseEntry:
    """Unified parse result for any file type.

    This replaces:
    - AST dicts from stage1_syntax (for source code)
    - TemplateParseResult.to_dict() (for templates)
    - JavaConfigResult.to_dict() (for framework configs)
    - Dependency lists (for build files)
    - dict entries (for app configs)
    """
    file: str
    kind: FileType = "java"
    elements: list[dict] = field(default_factory=list)
    parse_error: bool = False
    error_msg: Optional[str] = None
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "file": self.file,
            "kind": self.kind,
            "elements": self.elements,
            "parse_error": self.parse_error,
            "error_msg": self.error_msg,
            "metadata": self.metadata,
        }

    @classmethod
    def from_ast(cls, entry: dict) -> "ParseEntry":
        """Convert a stage1_syntax AST entry to ParseEntry."""
        return cls(
            file=entry["file"],
            kind="java",
            elements=[],  # raw AST stored in stage JSON, not here
            parse_error=entry.get("parse_error", False),
            error_msg=entry.get("error_msg"),
            metadata={"ast": entry.get("ast")},
        )

    @classmethod
    def from_template(cls, result) -> "ParseEntry":
        """Convert a TemplateParseResult to ParseEntry."""
        d = result.to_dict() if hasattr(result, "to_dict") else result
        return cls(
            file=d["file"],
            kind=d.get("kind", "template"),
            elements=d.get("elements", []),
            parse_error=d.get("parse_error", False),
            error_msg=d.get("error_msg"),
            metadata={},
        )


def _print_intra_type_summary(edges: list) -> None:
    """Print a summary of Intra-Type edge kinds from the subgraph's edge list.

    Intra-Type edges are cross-file edges of the same type generated by language plugins
    in Stage 4: imports, extends, implements, inner_class, and the named variants
    (js_import, ts_import, py_import, java_extends, etc.).
    """
    if not edges:
        return
    from collections import Counter
    all_kinds = Counter(e.kind if hasattr(e, "kind") else e.get("kind", "") for e in edges)
    # Intra-Type kinds are cross-file structural references (not internal)
    # NOTE: inner_class is excluded because it represents a SAME-FILE relationship
    #       (nested class definition), not a cross-file relationship.
    intra_kinds = {
        "imports", "extends", "implements",
        "js_import", "ts_import", "py_import", "java_import", "go_import",
        "jsp_include", "cpp_include",
        "java_extends", "java_implements",
    }
    intra_total = sum(cnt for k, cnt in all_kinds.items() if k in intra_kinds)
    if intra_total > 0:
        parts = [f"{k}={cnt}" for k, cnt in sorted(all_kinds.items()) if k in intra_kinds]
        print(f"  [Stage 2]   Intra-Type edges: {intra_total}  ({', '.join(parts)})")


@dataclass
class SubgraphStats:
    """Statistics for a subgraph."""
    file_count: int = 0
    parse_failed: int = 0
    nodes: int = 0
    edges: int = 0
    elements: int = 0


# ══════════════════════════════════════════════════════════════════════════════
#  FileTypeHandler Protocol — one implementation per file-type category
# ══════════════════════════════════════════════════════════════════════════════

class SourceCodeHandler:
    """Handler for source code files (java, python, javascript, go, cpp).

    Pipeline: parse_directory → build_symbol_table → infer_types
             → resolve_references → semantic_enrichment → subgraph
    """

    def __init__(self, lang: str):
        self.lang = lang

    @property
    def name(self) -> str:
        return self.lang

    def parse(self, src_root: Path, files: list[Path]) -> list[ParseEntry]:
        from stage1_syntax import _parse_files_with_lang
        ast_data = _parse_files_with_lang(src_root, self.lang, files)
        return [ParseEntry.from_ast(e) for e in ast_data]

    def build_subgraph(self, src_root: Path, entries: list[ParseEntry],
                      full_graph: bool = False) -> tuple[dict, SubgraphStats]:
        """Run the full source-code pipeline and return (enriched graph dict, stats)."""
        ast_data = [
            {"file": e.file, "ast": e.metadata.get("ast"), "parse_error": e.parse_error}
            for e in entries
        ]

        # Stage 2: build symbols (progress bar inside stage2_symbols.py)
        sym_data = build_symbol_table(ast_data, self.lang, str(src_root))
        # Stage 3: infer types (in-memory, fast)
        typed_data = infer_types(sym_data)
        # Stage 4: resolve references
        refs_data = resolve_references(typed_data, ast_data, None, self.lang,
                                      filter_quality=not full_graph)
        # Stage 5: semantic enrichment
        graph = semantic_enrichment(refs_data, None, self.lang,
                                    skip_prune=full_graph)

        return graph, SubgraphStats(
            file_count=len(entries),
            parse_failed=sum(1 for e in entries if e.parse_error),
            nodes=len(graph.get("symbols", [])),
            edges=len(graph.get("edges", [])),
            elements=0,
        )

    def write_jsonl(self, graph: dict, ast_data: list[dict], ui_data: dict,
                   out_dir: Path, full_graph: bool = False):
        _write_jsonl_from_graph(graph=graph, ast_data=ast_data, ui_data=ui_data,
                              out_dir=out_dir, full_graph=full_graph)
        _write_method_bodies(graph, ast_data, out_dir)


class TemplateHandler:
    """Handler for template files (jsp, jinja2, react, vue, go_template)."""

    def __init__(self, lang: str):
        self.lang = lang  # the template plugin name

    @property
    def name(self) -> str:
        return self.lang

    def parse(self, src_root: Path, files: list[Path]) -> list[ParseEntry]:
        try:
            from plugins.tpl_02_template.web_pages import TemplateRegistry
        except ImportError:
            from .plugins.tpl_02_template.web_pages import TemplateRegistry

        entries = []
        for fp in tqdm(files, desc=f"  Parsing {self.lang}", unit="file", ncols=80):
            result = TemplateRegistry.parse_file(fp)
            # Skip files that don't contain template syntax (e.g., plain HTML)
            if result is None:
                continue
            entries.append(ParseEntry.from_template(result))
        return entries

    def build_subgraph(self, src_root: Path, entries: list[ParseEntry],
                      full_graph: bool = False) -> tuple[list[dict], list[dict], SubgraphStats]:
        """Build a subgraph from template elements.

        Nodes: template file nodes + element nodes
        Edges: contains (file → element)
        """
        symbols, edges = [], []
        for entry in entries:
            fp = entry.file
            fname = Path(fp).name if fp else "unknown"
            file_node_id = f"template::{fp}"
            symbols.append({
                "qualified_name": file_node_id,
                "name": fname,
                "kind": "template_page",
                "file": fp,
                "lang": self.lang,
            })

            for elem in entry.elements:
                tag = elem.get("tag_name", "")
                line = elem.get("line", 0)
                elem_id = f"template::{fp}#{line}"
                symbols.append({
                    "qualified_name": elem_id,
                    "name": tag,
                    "kind": elem.get("kind", "template_element"),
                    "file": fp,
                    "line": line,
                    "tag_name": tag,
                    "attrs": elem.get("attrs", {}),
                    "lang": self.lang,
                })
                edges.append({
                    "kind": "contains",
                    "from_qname": file_node_id,
                    "to_qname": elem_id,
                    "file": fp,
                    "line": line,
                })

        return symbols, edges, SubgraphStats(
            file_count=len(entries),
            parse_failed=sum(1 for e in entries if e.parse_error),
            nodes=len(symbols),
            edges=len(edges),
            elements=sum(len(e.elements) for e in entries),
        )

    def write_jsonl(self, symbols: list[dict], edges: list[dict],
                   entries: list[ParseEntry], out_dir: Path, full_graph: bool = False):
        nodes_path = out_dir / "nodes.jsonl"
        edges_path = out_dir / "edges.jsonl"

        with nodes_path.open("w", encoding="utf-8") as f:
            for sym in symbols:
                node = {
                    "id": sym["qualified_name"],
                    "label": sym.get("name", ""),
                    "kind": sym.get("kind", "template"),
                    "file": sym.get("file", ""),
                    "start": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "end": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "lang": sym.get("lang", ""),
                }
                for k in ("tag_name", "attrs"):
                    if k in sym:
                        node[k] = sym[k]
                f.write(json.dumps(node, ensure_ascii=False) + "\n")

        with edges_path.open("w", encoding="utf-8") as f:
            for edge in edges:
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")


class ConfigHandler:
    """Handler for config files (yaml, json, properties, env, etc.)."""

    def __init__(self, lang: str):
        self.lang = lang  # the config plugin name

    @property
    def name(self) -> str:
        return self.lang

    def parse(self, src_root: Path, files: list[Path]) -> list[ParseEntry]:
        try:
            from plugins.cfg_03_config.app_config import ConfigRegistry
        except ImportError:
            from .plugins.cfg_03_config.app_config import ConfigRegistry

        entries = []
        for fp in tqdm(files, desc=f"  Parsing {self.lang}", unit="file", ncols=80):
            result = ConfigRegistry.parse_file(fp)
            if result:
                d = result if isinstance(result, dict) else result
                entries.append(ParseEntry(
                    file=str(fp),
                    kind=self.lang,
                    elements=d.get("entries", []),
                    parse_error=d.get("parse_error", False),
                    metadata=d,
                ))
            else:
                entries.append(ParseEntry(file=str(fp), kind=self.lang, parse_error=True))
        return entries

    def build_subgraph(self, src_root: Path, entries: list[ParseEntry],
                      full_graph: bool = False) -> tuple[list[dict], list[dict], SubgraphStats]:
        symbols, edges = [], []
        for entry in entries:
            fp = entry.file
            fname = Path(fp).name if fp else "unknown"
            file_node_id = f"config::{fp}"
            symbols.append({
                "qualified_name": file_node_id,
                "name": fname,
                "kind": "config_file",
                "file": fp,
                "lang": self.lang,
            })

            for idx, ce in enumerate(entry.elements):
                ce_kind = ce.get("entry_type", "config_entry")
                ce_name = ce.get("name", ce.get("key", f"entry_{idx}"))
                # Use tag:: prefix for TLD tags to match cross-file edge conventions
                if ce_kind == "tld_tag":
                    ce_id = f"tag::{ce_name}"
                else:
                    ce_id = f"config::{fp}#{ce_kind}#{idx}"
                ce_line = ce.get("line", 0)
                symbols.append({
                    "qualified_name": ce_id,
                    "name": ce_name,
                    "kind": ce_kind,
                    "file": fp,
                    "line": ce_line,
                    "attrs": {k: v for k, v in ce.items() if k not in ("entry_type", "name", "key", "line")},
                    "lang": self.lang,
                })
                edges.append({
                    "kind": "contains",
                    "from_qname": file_node_id,
                    "to_qname": ce_id,
                    "file": fp,
                    "line": ce_line or 1,
                })

        return symbols, edges, SubgraphStats(
            file_count=len(entries),
            parse_failed=sum(1 for e in entries if e.parse_error),
            nodes=len(symbols),
            edges=len(edges),
            elements=sum(len(e.elements) for e in entries),
        )

    def write_jsonl(self, symbols: list[dict], edges: list[dict],
                   entries: list[ParseEntry], out_dir: Path, full_graph: bool = False):
        nodes_path = out_dir / "nodes.jsonl"
        edges_path = out_dir / "edges.jsonl"

        with nodes_path.open("w", encoding="utf-8") as f:
            for sym in symbols:
                node = {
                    "id": sym["qualified_name"],
                    "label": sym.get("name", ""),
                    "kind": sym.get("kind", "config"),
                    "file": sym.get("file", ""),
                    "start": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "end": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "lang": sym.get("lang", ""),
                }
                if "attrs" in sym:
                    node["attrs"] = sym["attrs"]
                f.write(json.dumps(node, ensure_ascii=False) + "\n")

        with edges_path.open("w", encoding="utf-8") as f:
            for edge in edges:
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")


class BuildHandler:
    """Handler for build system files (maven, gradle, npm, pip, go_mod)."""

    def __init__(self, lang: str):
        self.lang = lang

    @property
    def name(self) -> str:
        return self.lang

    def parse(self, src_root: Path, files: list[Path]) -> list[ParseEntry]:
        try:
            from plugins.cfg_03_config.build import BuildRegistry
        except ImportError:
            from .plugins.cfg_03_config.build import BuildRegistry

        entries = []
        for fp in tqdm(files, desc=f"  Parsing {self.lang}", unit="file", ncols=80):
            result = BuildRegistry.parse_file(fp)
            if result:
                deps = result if isinstance(result, list) else []
                entries.append(ParseEntry(
                    file=str(fp),
                    kind=self.lang,
                    elements=[
                        {
                            "entry_type": "dependency",
                            "name": dep.artifact_id,
                            "group_id": dep.group_id,
                            "version": dep.version,
                            "scope": dep.scope,
                            "line": dep.line,
                        }
                            for dep in deps
                    ],
                    parse_error=False,
                ))
            else:
                entries.append(ParseEntry(file=str(fp), kind=self.lang, parse_error=True))
        return entries

    def build_subgraph(self, src_root: Path, entries: list[ParseEntry],
                      full_graph: bool = False) -> tuple[list[dict], list[dict], SubgraphStats]:
        symbols, edges = [], []
        for entry in entries:
            fp = entry.file
            fname = Path(fp).name if fp else "unknown"
            file_node_id = f"build::{fp}"
            symbols.append({
                "qualified_name": file_node_id,
                "name": fname,
                "kind": "build_file",
                "file": fp,
                "lang": self.lang,
            })

            for idx, ce in enumerate(entry.elements):
                ce_id = f"build::{fp}#dep#{idx}"
                symbols.append({
                    "qualified_name": ce_id,
                    "name": ce.get("name", ""),
                    "kind": "dependency",
                    "file": fp,
                    "line": ce.get("line", 0),
                    "attrs": {k: v for k, v in ce.items() if k != "line"},
                    "lang": self.lang,
                })
                edges.append({
                    "kind": "contains",
                    "from_qname": file_node_id,
                    "to_qname": ce_id,
                    "file": fp,
                    "line": ce.get("line", 0) or 1,
                })

        return symbols, edges, SubgraphStats(
            file_count=len(entries),
            parse_failed=sum(1 for e in entries if e.parse_error),
            nodes=len(symbols),
            edges=len(edges),
            elements=sum(len(e.elements) for e in entries),
        )

    def write_jsonl(self, symbols: list[dict], edges: list[dict],
                   entries: list[ParseEntry], out_dir: Path, full_graph: bool = False):
        nodes_path = out_dir / "nodes.jsonl"
        edges_path = out_dir / "edges.jsonl"

        with nodes_path.open("w", encoding="utf-8") as f:
            for sym in symbols:
                node = {
                    "id": sym["qualified_name"],
                    "label": sym.get("name", ""),
                    "kind": sym.get("kind", "build"),
                    "file": sym.get("file", ""),
                    "start": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "end": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "lang": sym.get("lang", ""),
                }
                if "attrs" in sym:
                    node["attrs"] = sym["attrs"]
                f.write(json.dumps(node, ensure_ascii=False) + "\n")

        with edges_path.open("w", encoding="utf-8") as f:
            for edge in edges:
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")

        ui_data = {}
        for entry in entries:
            if self.lang not in ui_data:
                ui_data[self.lang] = []
            ui_data[self.lang].append({
                "file": entry.file,
                "elements": entry.elements,
                "parse_error": entry.parse_error,
                "error_msg": entry.error_msg,
            })




class FrameworkHandler:
    """Handler for Java framework config files (tld, struts_config, web_xml, dicon)."""

    def __init__(self, lang: str):
        self.lang = lang

    @property
    def name(self) -> str:
        return self.lang

    def parse(self, src_root: Path, files: list[Path]) -> list[ParseEntry]:
        try:
            from plugins.cfg_03_config.framework.java import JavaConfigRegistry
        except ImportError:
            from .plugins.cfg_03_config.framework.java import JavaConfigRegistry

        entries = []
        for fp in tqdm(files, desc=f"  Parsing {self.lang}", unit="file", ncols=80):
            result = JavaConfigRegistry.parse_file(fp)
            if result:
                d = result.to_dict() if hasattr(result, "to_dict") else result
                entries.append(ParseEntry(
                    file=str(fp),
                    kind=self.lang,
                    elements=d.get("entries", []),
                    parse_error=d.get("parse_error", False),
                ))
            else:
                entries.append(ParseEntry(file=str(fp), kind=self.lang, parse_error=True))
        return entries

    def build_subgraph(self, src_root: Path, entries: list[ParseEntry],
                      full_graph: bool = False) -> tuple[list[dict], list[dict], SubgraphStats]:
        symbols, edges = [], []
        for entry in entries:
            fp = entry.file
            fname = Path(fp).name if fp else "unknown"
            file_node_id = f"config::{fp}"
            symbols.append({
                "qualified_name": file_node_id,
                "name": fname,
                "kind": "config_file",
                "file": fp,
                "lang": self.lang,
            })

            for idx, ce in enumerate(entry.elements):
                ce_kind = ce.get("entry_type", "config_entry")
                ce_name = ce.get("name", ce.get("key", f"entry_{idx}"))
                # Use tag:: prefix for TLD tags to match cross-file edge conventions
                if ce_kind == "tld_tag":
                    ce_id = f"tag::{ce_name}"
                else:
                    ce_id = f"config::{fp}#{ce_kind}#{idx}"
                ce_line = ce.get("line", 0)
                symbols.append({
                    "qualified_name": ce_id,
                    "name": ce_name,
                    "kind": ce_kind,
                    "file": fp,
                    "line": ce_line,
                    "attrs": {k: v for k, v in ce.items() if k not in ("entry_type", "name", "key", "line")},
                    "lang": self.lang,
                })
                edges.append({
                    "kind": "contains",
                    "from_qname": file_node_id,
                    "to_qname": ce_id,
                    "file": fp,
                    "line": ce_line or 1,
                })

        return symbols, edges, SubgraphStats(
            file_count=len(entries),
            parse_failed=sum(1 for e in entries if e.parse_error),
            nodes=len(symbols),
            edges=len(edges),
            elements=sum(len(e.elements) for e in entries),
        )

    def write_jsonl(self, symbols: list[dict], edges: list[dict],
                   entries: list[ParseEntry], out_dir: Path, full_graph: bool = False):
        nodes_path = out_dir / "nodes.jsonl"
        edges_path = out_dir / "edges.jsonl"

        with nodes_path.open("w", encoding="utf-8") as f:
            for sym in symbols:
                node = {
                    "id": sym["qualified_name"],
                    "label": sym.get("name", ""),
                    "kind": sym.get("kind", "config"),
                    "file": sym.get("file", ""),
                    "start": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "end": [sym.get("line", 1), 0] if sym.get("line") else None,
                    "lang": sym.get("lang", ""),
                }
                if "attrs" in sym:
                    node["attrs"] = sym["attrs"]
                f.write(json.dumps(node, ensure_ascii=False) + "\n")

        with edges_path.open("w", encoding="utf-8") as f:
            for edge in edges:
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")

        ui_data = {}
        for entry in entries:
            if self.lang not in ui_data:
                ui_data[self.lang] = []
            ui_data[self.lang].append({
                "file": entry.file,
                "elements": entry.elements,
                "parse_error": entry.parse_error,
                "error_msg": entry.error_msg,
            })




# ── Registry for file-type handlers ──────────────────────────────────────

_SOURCE_LANGS = {"java", "python", "javascript", "go", "cpp"}
_TEMPLATE_LANGS = {"jsp", "jinja2", "react", "vue", "html_template"}
_FRAMEWORK_LANGS = {"tld", "struts_config", "web_xml", "dicon"}
_CONFIG_LANGS = {"yaml", "json", "properties", "env"}


def get_handler(type_name: str) -> Optional[object]:
    """Get the appropriate FileTypeHandler for a type name."""
    if type_name in _SOURCE_LANGS:
        return SourceCodeHandler(type_name)
    if type_name in _TEMPLATE_LANGS:
        return TemplateHandler(type_name)
    if type_name in _FRAMEWORK_LANGS:
        return FrameworkHandler(type_name)
    if type_name in _CONFIG_LANGS:
        return ConfigHandler(type_name)
    return None


# ══════════════════════════════════════════════════════════════════════════════
#  Unified run_for_type() — one function for all file types
# ══════════════════════════════════════════════════════════════════════════════

def run_for_type(src_root: Path, out_dir: Path, type_name: str,
                files: list[Path], do_full_graph: bool = False) -> SubgraphStats:
    """Unified subgraph builder for all file types.

    Three-stage pipeline (replaces the old 5-stage for source, stage1b for templates,
    and ad-hoc config parsing):

    Stage 1: Parse    → ParseEntry list (AST / elements / entries)
    Stage 2: Subgraph → nodes + intra-type edges
    Stage 3: Write    → nodes.jsonl + edges.jsonl

    Args:
        src_root: Source project root
        out_dir:  Output directory for this subgraph
        type_name: File type identifier (e.g. "java", "jsp", "yaml")
        files:    Pre-classified list of files to parse
        full_graph: If True, output all nodes/edges (no pruning)

    Returns:
        SubgraphStats with file counts and node/edge counts
    """
    handler = get_handler(type_name)
    if handler is None:
        print(f"  [WARN] No handler for type: {type_name}")
        return SubgraphStats()

    out_dir.mkdir(parents=True, exist_ok=True)

    # Stage 1: Parse (handler.parse shows tqdm progress internally)
    print(f"  [Stage 1] Parsing {type_name.upper()} in {src_root}...")
    entries = handler.parse(src_root, files)
    failed = sum(1 for e in entries if e.parse_error)
    ok_count = len(entries) - failed
    print(f"  [Stage 1]   {ok_count} OK, {failed} failed out of {len(entries)} files")

    # Stage 2: Build subgraph
    print(f"  [Stage 2] Building subgraph...")
    if type_name in _SOURCE_LANGS:
        # Source code: use SourceCodeHandler with AST parsing
        ast_data = [
            {"file": e.file, "ast": e.metadata.get("ast"), "parse_error": e.parse_error}
            for e in entries
        ]
        graph, stats = handler.build_subgraph(src_root, entries, full_graph=do_full_graph)
        print(f"  [Stage 2]   {stats.nodes} nodes, {stats.edges} edges")
        _print_intra_type_summary(graph.get("edges", []))

        # Stage 3: Write JSONL
        print(f"  [Stage 3] Writing subgraph...")
        # For source code, ui_data is not needed for template edge resolution
        handler.write_jsonl(graph=graph, ast_data=ast_data, ui_data={},
                          out_dir=out_dir, full_graph=do_full_graph)
    else:
        symbols, edges, stats = handler.build_subgraph(src_root, entries, full_graph=do_full_graph)
        print(f"  [Stage 2]   {stats.nodes} nodes, {stats.edges} edges")
        _print_intra_type_summary(edges)

        # Stage 3: Write JSONL
        print(f"  [Stage 3] Writing subgraph...")
        handler.write_jsonl(symbols=symbols, edges=edges, entries=entries,
                         out_dir=out_dir, full_graph=do_full_graph)

    # Build per-type viewer (optional, lightweight)
    _build_viewer(out_dir)

    return stats


def run(src_root: Path, out_dir: Path, lang: str = "java",
         full_graph: bool = False) -> dict:
    """Run the 5-stage pipeline for a single language.

    Args:
        src_root: Source code directory to analyze.
        out_dir: Output directory for graph files.
        lang: Language plugin to use. Default: "java".
              Valid: "java", "python", "javascript", "go", "cpp".
        full_graph: If True, output full graph (all tiers, all nodes).
                    If False (default), output filtered graph (CORE tier only,
                    no reachability pruning overhead).
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Stage 1: Syntax Parsing ({lang})...")
    ast_data = parse_directory(src_root, lang)
    (out_dir / "stage1_ast.json").write_text(
        json.dumps(ast_data, ensure_ascii=False, indent=2), encoding="utf-8")
    failed = [e for e in ast_data if e.get("parse_error")]
    print(f"  {len(ast_data)} files parsed, {len(failed)} failed")

    print(f"Stage 2: Symbol Table Building...")
    sym_data = build_symbol_table(ast_data, lang, str(src_root))
    (out_dir / "stage2_symbols.json").write_text(
        json.dumps(sym_data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  {len(sym_data['symbols'])} symbols")

    print(f"Stage 3: Type Inference...")
    typed_data = infer_types(sym_data)
    (out_dir / "stage3_typed.json").write_text(
        json.dumps(typed_data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  types resolved")

    # ── Parse templates using unified TemplateRegistry ───────────────────────────
    print(f"Stage 1b: UI Parsing ({lang} templates)...")
    ui_data = {}
    
    try:
        from plugins.tpl_02_template.web_pages import TemplateRegistry
    except ImportError:
        from .plugins.tpl_02_template.web_pages import TemplateRegistry
    
    template_plugins = TemplateRegistry.get_for_lang(lang)
    for plugin in template_plugins:
        for pattern in plugin.file_patterns:
            for fp in src_root.rglob(pattern):
                result = TemplateRegistry.parse_file(fp)
                if result is None:
                    continue
                d = result.to_dict()
                kind = plugin.legacy_result_key or plugin.name
                if kind not in ui_data:
                    ui_data[kind] = []
                ui_data[kind].append(d)
                if "templates" not in ui_data:
                    ui_data["templates"] = []
                ui_data["templates"].append(d)

    jsp_ok = sum(1 for e in ui_data.get("jsp", []) if not e.get("parse_error"))
    jinja2_ok = sum(1 for e in ui_data.get("jinja2", []) if not e.get("parse_error"))
    react_ok = sum(1 for e in ui_data.get("react", []) if not e.get("parse_error"))
    vue_ok = sum(1 for e in ui_data.get("vue", []) if not e.get("parse_error"))
    print(f"  {jsp_ok} JSP, {jinja2_ok} Jinja2, {react_ok} React, {vue_ok} Vue files")

    print(f"Stage 4: Reference Resolution...")
    refs_data = resolve_references(typed_data, ast_data, ui_data, lang,
                                   filter_quality=not full_graph)
    (out_dir / "stage4_refs.json").write_text(
        json.dumps(refs_data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  {len(refs_data['edges'])} edges")

    print(f"Stage 5: Semantic Enrichment...")
    graph = semantic_enrichment(refs_data, ui_data, lang, skip_prune=full_graph)
    (out_dir / "stage5_graph.json").write_text(
        json.dumps(graph, ensure_ascii=False, indent=2), encoding="utf-8")

    _write_jsonl_from_graph(graph, ast_data, ui_data, out_dir, full_graph=full_graph)
    _write_method_bodies(graph, ast_data, out_dir)

    # Count actual entry points and web_action nodes from graph
    entry_pts = graph.get("entry_points", [])
    web_action_count = sum(
        1 for s in graph.get("symbols", [])
        if s.get("control_flow") == "web_action"
    )
    stats = _compute_stats(out_dir, entry_points=len(entry_pts),
                           web_action_count=web_action_count)
    _build_viewer(out_dir)
    _print_summary(src_root, out_dir, ast_data, stats, lang, full_graph=full_graph)

    return graph


def _write_config_jsonl(graph: dict, out_dir: Path):
    """Write nodes.jsonl and edges.jsonl for a config subgraph."""
    nodes_path = out_dir / "nodes.jsonl"
    edges_path = out_dir / "edges.jsonl"

    with nodes_path.open("w", encoding="utf-8") as f:
        for sym in graph["symbols"]:
            node = {
                "id": sym["qualified_name"],
                "label": sym.get("name", ""),
                "kind": sym.get("kind", "config"),
                "file": sym.get("file", ""),
                "start": [sym.get("line", 1), 0] if sym.get("line") else None,
                "end": [sym.get("line", 1), 0] if sym.get("line") else None,
                "lang": sym.get("lang", ""),
            }
            if "attrs" in sym:
                node["attrs"] = sym["attrs"]
            f.write(json.dumps(node, ensure_ascii=False) + "\n")

    with edges_path.open("w", encoding="utf-8") as f:
        for edge in graph["edges"]:
            f.write(json.dumps(edge, ensure_ascii=False) + "\n")


def run_all(src_root: Path, out_dir: Path,
            full_graph: bool = False) -> dict:
    """New --all mode: classify files → unified subgraph pipeline → cross-file edges.

    Output structure:
        output/
        ├── 01_source/backend/
        │   └── nodes.jsonl, edges.jsonl   (all source types merged)
        ├── 02_template/web_pages/
        │   └── nodes.jsonl, edges.jsonl  (all template types merged)
        ├── 03_config/app_config/
        ├── 03_config/framework/java/
        ├── cross_file_edges.json
        └── all_graph.json

    Args:
        src_root: Source code directory to analyze.
        out_dir: Output directory for graph files.
        full_graph: If True, output full graph (all tiers, all nodes).

    Returns:
        Master graph dict
    """
    print(f"\n{'='*60}")
    print(f"Stage 0: Project File Classification")
    print(f"{'='*60}")

    # Stage 0: classify all project files into role architecture categories
    classification = classify_project_files(src_root)
    print_classification_summary(classification)

    # Build output structure (creates all directories, even empty ones)
    build_output_structure(out_dir)

    # ── Phase 1: Build subgraphs per (category, handler) ─────────────────────
    all_subgraph_dirs: list[Path] = []

    for category in sorted(classification.keys()):
        files = classification[category]
        if not files:
            continue

        layer, subcat = category.split("/", 1)
        category_out = out_dir / layer / subcat
        category_out.mkdir(parents=True, exist_ok=True)

        print(f"\n{'='*60}")
        print(f"Processing category: {layer}/{subcat}")
        print(f"  Total files: {len(files)}")
        print(f"{'='*60}")

        # Group files by which handler can process them
        type_groups = _group_files_by_handler(files)
        if not type_groups:
            skipped = [str(fp).replace(str(src_root), "").lstrip(os.sep) for fp in files]
            print(f"  No supported file types ({len(files)} skipped): {', '.join(skipped)}")
            continue

        type_list = ", ".join(sorted(type_groups.keys()))
        print(f"  Detected {len(type_groups)} type(s): {type_list}")

        for type_name in sorted(type_groups.keys()):
            type_out = category_out / type_name
            type_out.mkdir(parents=True, exist_ok=True)
            all_subgraph_dirs.append(type_out)

            print(f"\n--- Parsing {type_name.upper()} files ({len(type_groups[type_name])} files) ---")
            run_for_type(src_root, type_out, type_name,
                        type_groups[type_name], do_full_graph=full_graph)

    # ── Phase 2: Merge all subgraphs ──────────────────────────────────────────
    print(f"\n{'='*60}")
    print(f"Merging Subgraphs")
    print(f"{'='*60}")
    print(f"  Collecting from {len(all_subgraph_dirs)} subgraph(s)...")

    _all_nodes = []
    _all_edges = []
    for sub_dir in all_subgraph_dirs:
        nodes_file = sub_dir / "nodes.jsonl"
        edges_file = sub_dir / "edges.jsonl"
        if nodes_file.exists():
            _all_nodes.extend(_load_jsonl(nodes_file))
        if edges_file.exists():
            _all_edges.extend(_load_jsonl(edges_file))

    print(f"  Merged: {len(_all_nodes)} nodes, {len(_all_edges)} edges")

    if _all_nodes:
        (out_dir / "nodes.jsonl").write_text(
            "\n".join(json.dumps(n, ensure_ascii=False) for n in _all_nodes),
            encoding="utf-8")
        (out_dir / "edges.jsonl").write_text(
            "\n".join(json.dumps(e, ensure_ascii=False) for e in _all_edges),
            encoding="utf-8")
        print(f"  Written: nodes.jsonl, edges.jsonl")

    # Guard: _build_viewer requires both files to exist
    if not (out_dir / "nodes.jsonl").exists() or not (out_dir / "edges.jsonl").exists():
        print(f"  Error: nodes.jsonl or edges.jsonl missing — cannot build viewer")
        print(f"  This may indicate all nodes were pruned (no code reachable from any file type).")
        return {}

    # ── Phase 3: Stage 6 — cross-file edge generation ─────────────────────────
    print(f"\n{'='*60}")
    print(f"Stage 6: Cross-File Edge Generation")
    print(f"{'='*60}")

    total_graph = generate_cross_file_edges(src_root, out_dir)

    # Build viewer for the master graph
    print(f"\n{'='*60}")
    print(f"Building Master Graph Viewer")
    print(f"{'='*60}")
    _build_viewer(out_dir)

    # Print final summary
    meta = total_graph.get("metadata", {})
    print(f"""
===== --all Pipeline Complete =====
Source:    {src_root}
Output:    {out_dir}
Subgraphs: {len(all_subgraph_dirs)} (across {len(classification)} categories)
Total nodes: {len(_all_nodes)}
Total edges: {len(_all_edges)}
Cross-file edges:
  Intra-Type:   {meta.get('intra_type_count', 0)}  (Stage 4: language plugins)
  Cross-Type:   {meta.get('cross_type_count', 0)}  (Stage 6: CrossFilePlugins)
  Cross-Layer:  {meta.get('cross_layer_count', 0)}  (Stage 6: CrossFilePlugins)
Output files:
  {out_dir / 'cross_file_edges.json'}
  {out_dir / 'all_graph.json'}
  {out_dir / 'graph_viewer.html'}
""")
    return total_graph


def _match_pattern(filename: str, pattern: str) -> bool:
    """Simple glob pattern match: *.java, *.py, *.js, etc."""
    import fnmatch
    return fnmatch.fnmatch(filename, pattern)


def _group_files_by_handler(files: list[Path]) -> dict[str, list[Path]]:
    """Group files by which handler will process them.

    Tries each handler in order:
      1. LanguageRegistry (source code: java, python, javascript, go, cpp)
      2. TemplateRegistry (templates: jsp, jinja2, react, vue, ...)
      3. JavaConfigRegistry (Java framework configs: tld, struts, web_xml, dicon)
      4. ConfigRegistry (app configs: yaml, json, properties, env)

    Returns dict: {type_name: [path, ...]}

    Files are assigned to the FIRST handler that matches them.
    Handlers are checked in priority order to avoid overlap
    (e.g., JSP files should go to TemplateRegistry, not BuildRegistry).
    """
    groups: dict[str, list[Path]] = defaultdict(list)
    assigned: set[str] = set()  # file paths already assigned

    for fp in files:
        fp_str = str(fp)
        if fp_str in assigned:
            continue

        # 1. Source code (LanguageRegistry — backend)
        from plugins.src_01_source.backend import LanguageRegistry
        for plugin in LanguageRegistry.all_plugins():
            for pat in plugin.get_file_patterns():
                if _match_pattern(fp.name, pat):
                    groups[plugin.lang_id].append(fp)
                    assigned.add(fp_str)
                    break
            if fp_str in assigned:
                break
        if fp_str in assigned:
            continue

        # 1b. Source code (LanguageRegistry — frontend, e.g. javascript)
        try:
            from plugins.src_01_source.frontend import LanguageRegistry as FrontendRegistry
            for plugin in FrontendRegistry.all_plugins():
                for pat in plugin.get_file_patterns():
                    if _match_pattern(fp.name, pat):
                        groups[plugin.lang_id].append(fp)
                        assigned.add(fp_str)
                        break
                if fp_str in assigned:
                    break
        except ImportError:
            pass
        if fp_str in assigned:
            continue

        # 2. Template (TemplateRegistry)
        try:
            from plugins.tpl_02_template.web_pages import TemplateRegistry
        except ImportError:
            from .plugins.tpl_02_template.web_pages import TemplateRegistry
        plugin = TemplateRegistry.get_for_file(fp)
        if plugin:
            groups[plugin.name].append(fp)
            assigned.add(fp_str)
            continue

        # 3. Java framework config (JavaConfigRegistry)
        try:
            from plugins.cfg_03_config.framework.java import JavaConfigRegistry
        except ImportError:
            from .plugins.cfg_03_config.framework.java import JavaConfigRegistry
        plugin = JavaConfigRegistry.get_for_file(fp)
        if plugin:
            groups[plugin.name].append(fp)
            assigned.add(fp_str)
            continue

        # 4. App config (ConfigRegistry)
        try:
            from plugins.cfg_03_config.app_config import ConfigRegistry
        except ImportError:
            from .plugins.cfg_03_config.app_config import ConfigRegistry
        plugins = ConfigRegistry.get_for_file(fp)
        if plugins:
            groups[plugins[0].name].append(fp)
            assigned.add(fp_str)
            continue

    return groups


def _detect_lang_for_category(category: str) -> Optional[str]:
    """Detect the language plugin ID for a role architecture category."""
    if "/java" in category or "/backend" in category:
        return "java"
    if "/python" in category:
        return "python"
    if "/javascript" in category or "/frontend" in category or "/vue" in category:
        return "javascript"
    if "/go" in category:
        return "go"
    if "/cpp" in category or "/embedded" in category:
        return "cpp"
    return None


def run_singlefile(src_root: Path, out_dir: Path,
                   file_type: str, full_graph: bool = False) -> dict:
    """New --singlefile mode: parse only the specified type, output subgraph + related cross-file edges.

    Workflow:
    1. Stage 0: Get the role for the specified file type
    2. Unified pipeline: parse → subgraph → write
    3. Stage 6: Generate cross-file edges for this type
    4. Output subgraph + related cross-file edges (NOT the complete master graph)

    Args:
        src_root: Source code directory to analyze.
        out_dir: Output directory for graph files.
        file_type: File type code (e.g., "java", "jsp", "yaml")
        full_graph: If True, output full graph (all tiers, all nodes).

    Returns:
        Subgraph dict with nodes, edges, and related cross-file edges
    """
    from stage0_classify import get_role_for_file_type

    role = get_role_for_file_type(file_type)
    if role is None:
        print(f"Unknown file type: {file_type}")
        print(f"Available types: {', '.join(sorted(FILE_TYPE_CODE_MAP.keys()))}")
        return {}

    layer, subcat = role
    category = f"{layer}/{subcat}"

    print(f"\n{'='*60}")
    print(f"Stage 0: File Type '{file_type}' -> {layer}/{subcat}")
    print(f"{'='*60}")

    # Build output structure
    build_output_structure(out_dir)
    category_out = out_dir / layer / subcat
    category_out.mkdir(parents=True, exist_ok=True)

    # Group files for this type using the unified handler
    from stage0_classify import classify_project_files
    classification = classify_project_files(src_root)
    files = classification.get(category, [])

    if not files:
        print(f"No files found for type: {file_type}")
        return {}

    # Filter to only the files for this type
    type_groups = _group_files_by_handler(files)
    type_files = type_groups.get(file_type, [])

    if not type_files:
        print(f"No files matched type: {file_type}")
        return {}

    print(f"Found {len(type_files)} files for type: {file_type}")

    # Run unified pipeline
    type_out = category_out / file_type
    type_out.mkdir(parents=True, exist_ok=True)
    run_for_type(src_root, type_out, file_type, type_files, do_full_graph=full_graph)

    # Stage 6: Cross-file edges for this type only
    print(f"\n{'='*60}")
    print(f"Stage 6: Cross-File Edge Generation for {file_type}")
    print(f"{'='*60}")

    result = generate_cross_file_edges_for_type(src_root, out_dir, file_type)

    print(f"""
===== --singlefile Pipeline Complete =====
Type:     {file_type}
Role:     {layer}/{subcat}
Files:    {len(type_files)}
Output:   {type_out}
""")
    return result


def _load_jsonl(path: Path) -> list[dict]:
    """Load all records from a JSONL file."""
    results = []
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                results.append(json.loads(line))
    return results


def _compute_stats(out_dir: Path, entry_points: int = 0, web_action_count: int = 0) -> dict:
    nodes_path = out_dir / "nodes.jsonl"
    edges_path = out_dir / "edges.jsonl"

    node_kinds = {}
    edge_kinds = {}
    all_domain_tags: set[str] = set()
    all_control_flows: set[str] = set()
    total_nodes = 0
    total_edges = 0

    with nodes_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            total_nodes += 1
            n = json.loads(line)
            k = n.get("kind", "unknown")
            node_kinds[k] = node_kinds.get(k, 0) + 1
            for tag in n.get("domain_tags") or []:
                all_domain_tags.add(tag)
            cf = n.get("control_flow")
            if cf:
                all_control_flows.add(cf)

    with edges_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            total_edges += 1
            e = json.loads(line)
            k = e.get("kind", "unknown")
            edge_kinds[k] = edge_kinds.get(k, 0) + 1

    call_edges = edge_kinds.get("call", 0)

    return {
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "node_kinds": node_kinds,
        "edge_kinds": edge_kinds,
        "domain_tags": sorted(all_domain_tags),
        "control_flows": sorted(all_control_flows),
        "call_edges": call_edges,
        "entry_points": entry_points,
        "web_action_count": web_action_count,
    }


def _print_summary(src_root: Path, out_dir: Path, ast_data: list, stats: dict,
                  lang: str, full_graph: bool = False):
    failed = [e for e in ast_data if e.get("parse_error")]
    total_files = len(ast_data)
    failed_files = len(failed)

    mode_label = "full" if full_graph else "filtered"
    node_lines = [f"  {k}: {v}" for k, v in sorted(stats["node_kinds"].items())]
    edge_lines = [f"  {k}: {v}" for k, v in sorted(stats["edge_kinds"].items())]
    tag_lines = [f"  {t}" for t in stats["domain_tags"]]

    print(f"""
===== 5stage Pipeline Complete =====
Mode:      {mode_label}
Language:  {lang}
Source:    {src_root}
Output:    {out_dir}
Files:     {total_files} total{f', {failed_files} failed' if failed_files else ''}
Nodes:     {stats['total_nodes']} total
{chr(10).join(node_lines)}
Edges:     {stats['total_edges']} total
{chr(10).join(edge_lines)}
Call edges:      {stats['call_edges']}
Entry points:    {stats['entry_points']}
  web_action:    {stats['web_action_count']}
Domain tags:     {len(stats['domain_tags'])} total
{chr(10).join(tag_lines)}
Output files:
  {out_dir / 'nodes.jsonl'}
  {out_dir / 'edges.jsonl'}
  {out_dir / 'method_bodies.jsonl'}
  {out_dir / 'graph_viewer.html'}
""")


def _write_jsonl_from_graph(graph: dict, ast_data: list[dict], ui_data: dict,
                 out_dir: Path, full_graph: bool = False):
    """Write nodes.jsonl and edges.jsonl from the enriched graph.

    Args:
        full_graph: If True, write all edge tiers and include external nodes.
                    If False (default), write CORE tier only with no external nodes.
    """
    reads_writes_mode = "all" if full_graph else "cross-class"
    include_external = full_graph
    include_layers = {TIER_CORE} if not full_graph else None

    # In filtered mode, exclude UI/template files for a pure code view
    exclude_ui_files: set[str] = set()
    if not full_graph:
        # Collect all UI/template file paths from all supported parsers
        for ui_key in ("jsp", "jinja2", "react", "vue", "html", "jsx", "tsx", "vue3"):
            for ui_file in ui_data.get(ui_key, []):
                if fp := ui_file.get("file"):
                    exclude_ui_files.add(fp)
                    exclude_ui_files.add(fp.replace("/", "\\"))
                    exclude_ui_files.add(fp.replace("\\", "/"))

    # Noise filter for ext:: names — skip expression fragments and bare identifiers
    def _is_noise_ext_name(name: str) -> bool:
        """Return True if this ext:: name looks like parser noise, not real code."""
        if not name:
            return True
        if "(" in name or ")" in name or "[" in name or "]" in name or "{" in name or "}" in name or " " in name:
            return True
        if "." not in name:
            return True
        return False

    nodes_path = out_dir / "nodes.jsonl"
    edges_path = out_dir / "edges.jsonl"

    # ── Phase 4: Migrate dep edges to node attributes ────────────────────────
    # Instead of writing N dep edges (root_module → dep1, root_module → dep2, ...),
    # we collect them per module and embed into the module's node.
    module_deps: dict[str, list[str]] = {}
    module_dep_kinds: dict[str, list[str]] = {}
    dep_edges_filtered: list[dict] = []
    for edge in graph["edges"]:
        kind = edge.get("kind", "")
        if kind.endswith(".dep"):
            fr = edge.get("from_qname", "")
            to = edge.get("to_coord", "") or edge.get("to_qname", "")
            if fr and to:
                module_deps.setdefault(fr, []).append(to)
                module_dep_kinds.setdefault(fr, []).append(kind)
        else:
            dep_edges_filtered.append(edge)
    graph["edges"] = dep_edges_filtered

    # ── Phase 5: Connectivity filter on remaining edges ───────────────────────
    # (Most filtering is done in stage4_refs._filter_edges_by_quality,
    #  but we do one more pass here to catch any edges added in stage5).
    # In full_graph mode, skip this filter — all edges are kept.
    def _has_connectivity(edge: dict) -> bool:
        fr = edge.get("from_qname", "")
        to = edge.get("to_qname", "")
        fr_in = is_in_main_cluster(fr) or is_cluster_adjacent(fr)
        to_in = is_in_main_cluster(to) or is_cluster_adjacent(to)
        return bool(fr_in or to_in)

    if not full_graph:
        pre_conn = len(graph["edges"])
        graph["edges"] = [e for e in graph["edges"] if _has_connectivity(e)]
        post_conn = len(graph["edges"])
        if post_conn < pre_conn:
            print(f"  connectivity filter: {pre_conn - post_conn} orphan edges removed")
    else:
        print(f"  [full mode] connectivity filter skipped")

    # ── Collect external stub nodes ─────────────────────────────────────────
    bound_to_ext_targets: set[str] = set()
    inheritance_ext_targets: set[str] = set()
    other_ext_targets: set[str] = set()
    for edge in graph["edges"]:
        to = edge.get("to_qname", "")
        if to.startswith("ext::"):
            kind = edge.get("kind", "")
            if kind == "bound_to":
                bound_to_ext_targets.add(to)
            elif kind in ("extends", "implements", "java_extends", "java_implements"):
                inheritance_ext_targets.add(to)
            else:
                other_ext_targets.add(to)
        frm = edge.get("from_qname", "")
        if frm.startswith("ext::") and edge.get("kind") == "contains":
            pass  # skip phantom contains from ext:: nodes
        elif frm.startswith("ext::"):
            other_ext_targets.add(frm)

    # ── Collect UI file paths ───────────────────────────────────────────────
    ui_file_paths: set[str] = set()
    for sym in graph["symbols"]:
        f = sym.get("file", "")
        qname = sym.get("qualified_name", "")
        if not f:
            continue
        if qname.startswith(("config::", "tag::")):
            continue
        # In filtered mode, skip JSP files for pure code view
        if not full_graph and f in exclude_ui_files:
            continue
        ui_file_paths.add(f)

    ast_files: set[str] = {e["file"] for e in ast_data}
    ast_files_norm: dict[str, str] = {}
    for p in ast_files:
        ast_files_norm[p.replace("/", "\\")] = p
        ast_files_norm[p.replace("\\", "/")] = p

    # Collect file IDs that have at least one surviving defined_in edge.
    # Symbols may have been pruned by reachability, leaving orphaned file nodes.
    files_with_edges: set[str] = set()
    for sym in graph["symbols"]:
        fp = sym.get("file", "")
        if fp:
            files_with_edges.add(fp)

    with nodes_path.open("w", encoding="utf-8") as f:
        # Deduplicate across all node types: symbols, file nodes, external stubs.
        # Use a single seen set so that a file node (file::path) is not written
        # if it was already emitted as a symbol node.
        seen_node_ids: set[str] = set()

        # File nodes from ast_data — only if at least one symbol survived pruning
        for entry in ast_data:
            if entry["file"] not in files_with_edges:
                continue  # skip orphaned file nodes
            # In filtered mode, skip UI/template files for pure code view
            if not full_graph and entry["file"] in exclude_ui_files:
                continue
            file_id = f"file::{entry['file']}"
            if file_id in seen_node_ids:
                continue
            seen_node_ids.add(file_id)
            file_node = {
                "id": file_id,
                "label": Path(entry["file"]).name,
                "kind": "file",
                "file": entry["file"],
                "parse_error": entry.get("parse_error", False),
                "error_msg": entry.get("error_msg"),
            }
            f.write(json.dumps(file_node, ensure_ascii=False) + "\n")

        # File nodes for UI assets (TLD, XML, etc.) not in ast_data
        # Only write if they have surviving symbols
        for ui_file in sorted(ui_file_paths):
            if not ui_file:
                continue
            if ui_file not in files_with_edges:
                continue  # skip orphaned UI file nodes
            ui_file_id = f"file::{ui_file}"
            if ui_file_id in seen_node_ids:
                continue
            seen_node_ids.add(ui_file_id)
            file_node = {
                "id": ui_file_id,
                "label": Path(ui_file).name,
                "kind": "file",
                "file": ui_file,
                "parse_error": False,
                "error_msg": None,
            }
            f.write(json.dumps(file_node, ensure_ascii=False) + "\n")

        # Symbol nodes (with embedded dependency metadata from Phase 4)
        for sym in graph["symbols"]:
            # In filtered mode, skip template-related symbols for pure code view
            if not full_graph:
                sym_kind = sym.get("kind", "")
                sym_file = sym.get("file", "")
                # Skip any symbol whose kind is a known UI/template kind
                if sym_kind in ("jsp_page", "jinja2_template", "react_component",
                                "vue_component", "html_page"):
                    continue
                # Skip symbols from known UI file extensions
                UI_EXTENSIONS = (".jsp", ".jspf", ".jspx",
                                 ".html", ".vue", ".jsx", ".tsx",
                                 ".jinja", ".jinja2", ".htm")
                if any(sym_file.lower().endswith(ext) for ext in UI_EXTENSIONS):
                    continue
            # Skip import symbols from the node layer.
            # They exist solely to help build "imports" edges (module → module) and
            # should not appear as nodes, because their qualified_name collides with
            # the actual symbol they reference (e.g. an import of "Foo" and the class
            # definition of "Foo" would both use "pkg.Foo" as id, producing duplicates).
            if sym.get("kind") == "import":
                continue

            # Deduplicate by qualified_name: skip if we've already written this symbol.
            node_id = sym["qualified_name"]
            if node_id in seen_node_ids:
                continue
            seen_node_ids.add(node_id)

            node = {
                "id": node_id,
                "label": sym.get("name") or sym.get("label", ""),
                "kind": sym["kind"],
                "file": sym.get("file", ""),
                "start": sym.get("start"),
                "end": sym.get("end"),
                "scope": sym.get("scope", ""),
                "type_hint": sym.get("type_hint"),
                "modifiers": sym.get("modifiers", []),
                "annotations": sym.get("annotations", []),
                "docstring": sym.get("docstring"),
                "domain_tags": sym.get("domain_tags", []),
                "control_flow": sym.get("control_flow"),
                "lang": sym.get("lang", "java"),
            }
            for k in ("url_pattern", "tag_usage", "custom_tags", "handler", "body_content", "is_entry"):
                if k in sym and sym[k] not in (None, []):
                    node[k] = sym[k]
            # Embed dependency metadata (Phase 4: dep edges → node attrs)
            qn = sym["qualified_name"]
            if qn in module_deps:
                deps = sorted(set(module_deps[qn]))
                kinds = sorted(set(module_dep_kinds.get(qn, [])))
                node["dependencies"] = deps[:100]  # cap at 100
                node["dependency_kinds"] = kinds
            f.write(json.dumps(node, ensure_ascii=False) + "\n")

        # External stub nodes + virtual file node (only when include_external=True)
        # Count real external nodes (after noise filter)
        real_other_ext = [q for q in other_ext_targets if not _is_noise_ext_name(q)]
        if bound_to_ext_targets or inheritance_ext_targets or (include_external and real_other_ext):
            ext_file_node = {
                "id": "file::external",
                "label": "external",
                "kind": "file",
                "file": None,
                "parse_error": False,
                "error_msg": None,
            }
            f.write(json.dumps(ext_file_node, ensure_ascii=False) + "\n")

        # bound_to handler nodes (always written)
        for ext_qname in sorted(bound_to_ext_targets):
            node = {
                "id": ext_qname,
                "label": ext_qname[5:],  # strip "ext::"
                "kind": "external",
                "file": None,
            }
            f.write(json.dumps(node, ensure_ascii=False) + "\n")

        # inheritance nodes (always written: shows class hierarchy)
        for ext_qname in sorted(inheritance_ext_targets):
            node = {
                "id": ext_qname,
                "label": ext_qname[5:],  # strip "ext::"
                "kind": "external",
                "file": None,
            }
            f.write(json.dumps(node, ensure_ascii=False) + "\n")

        # Other external nodes (only when include_external=True)
        # Noise is already filtered by _is_noise_ext_name (defined at top of function)
        if include_external:
            for ext_qname in sorted(other_ext_targets):
                if _is_noise_ext_name(ext_qname):
                    continue
                node = {
                    "id": ext_qname,
                    "label": ext_qname[5:],  # strip "ext::"
                    "kind": "external",
                    "file": None,
                }
                f.write(json.dumps(node, ensure_ascii=False) + "\n")

    # Build complete file → file::id mapping (ast_data + UI files)
    file_by_path: dict[str, str] = {e["file"]: f"file::{e['file']}" for e in ast_data}
    for ui_file in ui_file_paths:
        if ui_file and ui_file not in file_by_path:
            file_by_path[ui_file] = f"file::{ui_file}"

    # Build set of internal class qnames for reads/writes cross-class filtering
    internal_classes: set[str] = set()
    for sym in graph["symbols"]:
        if sym.get("kind") in ("class", "interface", "enum"):
            internal_classes.add(sym["qualified_name"])

    with edges_path.open("w", encoding="utf-8") as f:
        # defined_in edges: every symbol → its source file
        for sym in graph["symbols"]:
            file_id = file_by_path.get(sym.get("file", ""))
            if file_id:
                edge = {
                    "kind": "defined_in",
                    "from_qname": sym["qualified_name"],
                    "to_qname": file_id,
                    "file": sym.get("file", ""),
                    "line": sym.get("start", [1])[0] if sym.get("start") else 1,
                }
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")

        # defined_in edges: external stubs → virtual file::external node (only if include_external)
        if include_external:
            ext_file_id = "file::external"
            for ext_qname in sorted(other_ext_targets):
                edge = {
                    "kind": "defined_in",
                    "from_qname": ext_qname,
                    "to_qname": ext_file_id,
                    "file": "",
                    "line": 0,
                }
                f.write(json.dumps(edge, ensure_ascii=False) + "\n")

        # All other edges — with filtering (external, reads/writes, layer)
        for edge in graph["edges"]:
            kind = edge.get("kind", "")

            # ── Layer filter (Phase 5) ─────────────────────────────────────────
            if not full_graph:
                tier = KIND_TO_TIER.get(kind, "misc")
                if tier not in include_layers:
                    continue

            # Skip external edges when include_external=False
            if not include_external:
                if edge.get("to_qname", "").startswith("ext::"):
                    if kind not in ("bound_to", "extends", "implements", "java_extends", "java_implements"):
                        continue
                if edge.get("from_qname", "").startswith("ext::"):
                    continue

            # Filter reads/writes by mode
            if kind in ("reads", "writes"):
                if reads_writes_mode == "none":
                    continue

            f.write(json.dumps(edge, ensure_ascii=False) + "\n")


def _write_method_bodies(graph: dict, ast_data: list[dict], out_dir: Path):
    bodies_path = out_dir / "method_bodies.jsonl"
    method_ranges: dict[str, list[tuple[int, int, str]]] = defaultdict(list)
    for sym in graph["symbols"]:
        if sym.get("kind") in ("method", "function"):
            method_ranges[sym.get("file", "")].append(
                (sym.get("start", [1, 0])[0], sym.get("end", [1, 0])[0], sym["qualified_name"])
            )

    with bodies_path.open("w", encoding="utf-8") as fout:
        for entry in ast_data:
            if entry.get("parse_error"):
                continue
            file_path = entry["file"]
            if file_path not in method_ranges:
                continue
            try:
                lines = Path(file_path).read_text(encoding="utf-8").splitlines()
            except Exception:
                continue
            for start_line, end_line, qname in method_ranges[file_path]:
                start_idx = max(0, start_line - 1)
                end_idx = min(len(lines), end_line)
                body_text = "\n".join(lines[start_idx:end_idx])
                record = {
                    "qname": qname,
                    "file": file_path,
                    "start_line": start_line,
                    "end_line": end_line,
                    "body": body_text,
                }
                fout.write(json.dumps(record, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    import argparse

    parser_arg = argparse.ArgumentParser(
        description="Run the CodeGraph pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Modes:\n"
            "  --all          Classify all files by role architecture, parse each category,\n"
            "                  then generate cross-file edges into a master graph.\n"
            "  --singlefile   Parse only the specified file type, output its subgraph\n"
            "                  plus related cross-file edges (not the complete master graph).\n"
            "  --lang          Parse only the specified language (legacy mode).\n\n"
            "File type codes for --singlefile:\n"
            "  java, python, javascript, typescript, go, cpp\n"
            "  jsp, html, xml, yaml, json, properties, toml, gradle\n\n"
            "Examples:\n"
            "  python run_pipeline.py ./src ./output --all\n"
            "  python run_pipeline.py ./src ./output --singlefile java\n"
            "  python run_pipeline.py ./src ./output --lang python\n"
        ),
    )
    parser_arg.add_argument("src_root", nargs="?", type=Path, default=None,
                            help="Source code directory to analyze")
    parser_arg.add_argument("out_dir", nargs="?", type=Path, default=None,
                            help="Output directory for graph files")
    parser_arg.add_argument("--lang", choices=["java", "python", "javascript", "go", "cpp"],
                            default=None, help="Language plugin to use (legacy single-language mode)")
    parser_arg.add_argument("--all", action="store_true",
                            help="Role-architecture mode: parse all languages + generate cross-file edges")
    parser_arg.add_argument("--singlefile", type=str, default=None,
                            help="Parse only the specified file type (e.g., java, jsp, yaml)")
    parser_arg.add_argument("--auto", action="store_true",
                            help="Auto-discover src and out directories")
    parser_arg.add_argument("--mode",
                            choices=["filtered", "full"], default="filtered",
                            help="Output mode: 'filtered' (default, CORE layer only, "
                                 "compact code graph) or 'full' (all layers, "
                                 "UI + config + build + template edges)")

    args = parser_arg.parse_args()
    full_graph = (args.mode == "full")

    # Auto-discovery mode
    if args.auto or (args.src_root is None and args.out_dir is None):
        src = Path("src/main/java") if Path("src/main/java").exists() else Path("src")
        if not src.exists():
            src = Path(".")
        out = Path("output")
        print(f"  [auto mode: src={src}, out={out}]")
    else:
        src = args.src_root or Path(".")
        out = args.out_dir or Path("output")

    if args.all:
        # New --all mode: role architecture based
        # --all means comprehensive analysis: parse all types, generate all edges,
        # no pruning. Always use full_graph=True.
        run_all(src, out, full_graph=True)
    elif args.singlefile:
        # New --singlefile mode
        run_singlefile(src, out, args.singlefile, full_graph=full_graph)
    elif args.lang:
        # Legacy single-language mode
        run(src, out, args.lang, full_graph=full_graph)
    else:
        # Auto-detect single language
        from plugins.src_01_source.backend import LanguageRegistry
        plugins = LanguageRegistry.get_by_glob_patterns(src)
        if plugins:
            run(src, out, plugins[0].lang_id, full_graph=full_graph)
        else:
            print("No supported language files found. Defaulting to Java.")
            run(src, out, "java", full_graph=full_graph)
