package jp.co.rct.jj.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.seasar.struts.annotation.ActionForm;
import org.seasar.struts.annotation.Execute;

import jp.co.rct.jj.form.JJ901SOLR002Form;

/**
 * Elasticsearchのクエリをフォーマットして返却する
 * @author kaisho
 */
public class JJ901SOLR002Action {

	@ActionForm
	@Resource(name = "JJ901SOLR002Form")
	private JJ901SOLR002Form form;

	public HttpServletResponse response;

	/**
	 * テスト用メインメソッド
	 * @param args
	 * @throws UnsupportedEncodingException
	 */
	public static void main(String[] args) throws UnsupportedEncodingException {
		test("q=%28IS_S__SEACH__SERVICE_SHU_CD%3A040+AND+IS_MS__SEACH__KEISAI_SITE_KBN_LIST%3A01+AND+IS_S__SEACH__AREA_CD%3A030+AND+IS_S__SEACH__SHIKUGUN_KUKURI1_CD%3A13+AND+%28IS_S__SEACH__SHIKUGUN_KUKURI3_CD%3A101%29%29&start=-1294967356&rows=30&sort=I_F__SEACH__CHINRYO_KANRI_KOMI+asc%2CI_F__SEACH__MENSEKI1_F_SORT+desc%2CIS_I__SEACH__CM_FLG+desc%2CIS_I__SEACH__PANORAMA_FLG+desc%2CI_I__SEACH__GEN_SORT5+asc&fl=S_MS__SEACH__ICHIRAN_GAZO_LIST%2CIS_S__SEACH__KOTORI_SHU_NM%2CIS_T07__SEACH__BUKKEN_NM%2CS_S__SEACH__ENSEN_NM1%2CS_S__SEACH__EKI_NM1%2CS_S__SEACH__EKI_NM2%2CS_S__SEACH__EKI_NM3%2CS_S__SEACH__KAIDATE_DISP%2CS_S__SEACH__CHIKUGONENSU_DISP%2CIS_S__SEACH__SHINCHIKU_FLG%2CIS_T07__SEACH__JUSHO_DISP%2CS_S__SEACH__KOTSU_DISP%2CS_S__SEACH__KOTSU_DISP2%2CS_S__SEACH__KOTSU_DISP3%2CS_S__SEACH__CHIKUGONENSU_DISP%2CS_S__SEACH__KAIDATE_DISP%2CIS_S__SEACH__SHINCHIKU_FLG%2CIS_I__SEACH__HON_NEW_FLG%2CIS_I__SEACH__NEW_FLG%2CS_S__SEACH__KAISO_DISP%2CS_S__SEACH__CHINRYO_DISP%2CS_S__SEACH__KANRIHI_DISP%2CS_S__SEACH__SHIKIKIN_SIMPLE_DISP%2CS_S__SEACH__REIKIN_SIMPLE_DISP%2CS_S__SEACH__HOSHOKIN_DISP%2CS_S__SEACH__SHIKIBIKI_SHOKYAKUKIN_DISP%2CS_S__SEACH__MADORI_DISP%2CS_S__SEACH__MENSEKI1_DISP%2CIS_I__SEACH__CM_FLG%2CIS_S__SEACH__CM_SHU_CD%2CIS_I__SEACH__KOTSUBIN_CD%2CIS_S__SEACH__KOTSUBIN_CD2%2CIS_S__SEACH__KOTSUBIN_CD3%2CIS_S__SEACH__BUKKEN_CD%2CIS_S__SEACH__PERM_JUKO_NAYOSE_CD%2CIS_I__SEACH__JUKO_NAYOSE_SCORE%2CIS_S__SEACH__SHIKUGUN_KUKURI1_CD%2CIS_S__SEACH__SHIKUGUN_KUKURI3_CD%2CIS_S__SEACH__AREA_CD%2CS_S__SEACH__GAZO_SU%2CIS_S__SEACH__EKI_CD1%2CIS_S__SEACH__EKI_CD2%2CIS_S__SEACH__EKI_CD3%2CS_S__SEACH__BUS_JIKAN_DISP%2CS_S__SEACH__BUS_JIKAN_DISP2%2CS_S__SEACH__BUS_JIKAN_DISP3%2CS_S__SEACH__TOHO_JIKAN_DISP%2CS_S__SEACH__TOHO_JIKAN_DISP2%2CS_S__SEACH__TOHO_JIKAN_DISP3%2CIS_S__SEACH__TOU_NAYOSE_CD%2CIS_MS__SEACH__SONOTA_JOKEN%2Cid&group=true&group.ngroups=true&group.field=IS_S__SEACH__TOU_NAYOSE_CD&group.limit=12000&group.offset=0&group.facet=false&group.truncate=false&group.cache.percent=20");
		test("q=%28IS_S__SEACH__AREA_CD%3A090+AND+IS_S__SEACH__DISP_PRIORITY_FLG%3A1+AND+IS_S__SEACH__SERVICE_SHU_CD%3A010%29+AND+%28IS_S__SEACH__KAKAKU_MITEI_FLG%3A0+OR+IS_S__SEACH__KAKAKU_MITEI_FLG%3A1%29+AND+%28%28%28%28IS_S__SEACH__EKI_CD1%3A%2839180+OR+15440+OR+39170+OR+14700+OR+28750+OR+11880+OR+26290+OR+04890+OR+76205+OR+40150+OR+13170+OR+76210+OR+07300+OR+36810+OR+07390+OR+05080+OR+11910+OR+00420+OR+25640+OR+32290+OR+33730+OR+24150+OR+14510+OR+42610+OR+42620+OR+23900+OR+11870+OR+07850+OR+76215+OR+30350+OR+41000+OR+30190+OR+22880+OR+16300+OR+37750+OR+08040+OR+06150+OR+36740+OR+26330+OR+34370+OR+25470+OR+31370+OR+13090+OR+01520+OR+29430+OR+30160+OR+34450+OR+21200+OR+37580+OR+41770+OR+41030+OR+12230+OR+06340%29%29+AND+IS_I__SEACH__KOTSUBIN_CD%3A1+AND+IS_I__SEACH__TOHO_JIKAN%3A%5B1+TO+10%5D%29%29+OR+%28%28%28IS_S__SEACH__EKI_CD2%3A%2839180+OR+15440+OR+39170+OR+14700+OR+28750+OR+11880+OR+26290+OR+04890+OR+76205+OR+40150+OR+13170+OR+76210+OR+07300+OR+36810+OR+07390+OR+05080+OR+11910+OR+00420+OR+25640+OR+32290+OR+33730+OR+24150+OR+14510+OR+42610+OR+42620+OR+23900+OR+11870+OR+07850+OR+76215+OR+30350+OR+41000+OR+30190+OR+22880+OR+16300+OR+37750+OR+08040+OR+06150+OR+36740+OR+26330+OR+34370+OR+25470+OR+31370+OR+13090+OR+01520+OR+29430+OR+30160+OR+34450+OR+21200+OR+37580+OR+41770+OR+41030+OR+12230+OR+06340%29%29+AND+IS_S__SEACH__KOTSUBIN_CD2%3A1+AND+IS_I__SEACH__TOHO_JIKAN2%3A%5B1+TO+10%5D%29%29+OR+%28%28%28IS_S__SEACH__EKI_CD3%3A%2839180+OR+15440+OR+39170+OR+14700+OR+28750+OR+11880+OR+26290+OR+04890+OR+76205+OR+40150+OR+13170+OR+76210+OR+07300+OR+36810+OR+07390+OR+05080+OR+11910+OR+00420+OR+25640+OR+32290+OR+33730+OR+24150+OR+14510+OR+42610+OR+42620+OR+23900+OR+11870+OR+07850+OR+76215+OR+30350+OR+41000+OR+30190+OR+22880+OR+16300+OR+37750+OR+08040+OR+06150+OR+36740+OR+26330+OR+34370+OR+25470+OR+31370+OR+13090+OR+01520+OR+29430+OR+30160+OR+34450+OR+21200+OR+37580+OR+41770+OR+41030+OR+12230+OR+06340%29%29+AND+IS_S__SEACH__KOTSUBIN_CD3%3A1+AND+IS_I__SEACH__TOHO_JIKAN3%3A%5B1+TO+10%5D%29%29%29&start=0&rows=0");
		test("q=%28IS_S__SEACH__AREA_CD%3A090+AND+IS_S__SEACH__DISP_PRIORITY_FLG%3A1+AND+IS_S__SEACH__SERVICE_SHU_CD%3A010%29+AND+%28IS_S__SEACH__KAKAKU_MITEI_FLG%3A0+OR+IS_S__SEACH__KAKAKU_MITEI_FLG%3A1%29+AND+%28%28%28%28IS_S__SEACH__EKI_CD1%3A33200%29+AND+IS_I__SEACH__KOTSUBIN_CD%3A1+AND+IS_I__SEACH__TOHO_JIKAN%3A%5B1+TO+10%5D%29%29+OR+%28%28%28IS_S__SEACH__EKI_CD2%3A33200%29+AND+IS_S__SEACH__KOTSUBIN_CD2%3A1+AND+IS_I__SEACH__TOHO_JIKAN2%3A%5B1+TO+10%5D%29%29+OR+%28%28%28IS_S__SEACH__EKI_CD3%3A33200%29+AND+IS_S__SEACH__KOTSUBIN_CD3%3A1+AND+IS_I__SEACH__TOHO_JIKAN3%3A%5B1+TO+10%5D%29%29%29&start=0&rows=0");
		test("q=%28IS_S__SEACH__AREA_CD%3A030+AND+%28IS_S__SEACH__GAIBU_SYSTEM_KBN%3A%2800+OR+01%29%29%29+AND+%28IS_S__SEACH__SERVICE_SHU_CD%3A010+OR+IS_S__SEACH__SERVICE_SHU_CD%3A011+OR+%28%28%28IS_S__SEACH__SERVICE_SHU_CD%3A020%29+OR+%28%28IS_S__SEACH__SERVICE_SHU_CD%3A030+AND+IS_S__SEACH__KENCHIKUJOKEN_FLG%3A1%29%29%29%29+OR+IS_S__SEACH__SERVICE_SHU_CD%3A021+OR+IS_S__SEACH__SERVICE_SHU_CD%3A030+OR+%28%28I_S__SEACH__RYOUIKI_CD%3A301+AND+IS_MS__SEACH__KEISAI_SITE_KBN_LIST%3A01%29%29%29&start=0&rows=0&facet.limit=-1&facet.mincount=1&facet.field=IS_S__SEACH__EKI_CD2&facet=true");
		test("q=%28IS_S__SEACH__AREA_CD%3A090+AND+IS_I__SEACH__CHIKUGONENSU%3A%5B*+TO+9999999%5D+AND+IS_S__SEACH__DISP_PRIORITY_FLG%3A1+AND+IS_S__SEACH__KAKAKU_MITEI_FLG%3A0+AND+IS_S__SEACH__SERVICE_SHU_CD%3A011+AND+IS_S__SEACH__SHIKUGUN_KUKURI1_CD%3A40+AND+IS_S__SEACH__SHIKUGUN_KUKURI2_CD%3A02%29&start=0&rows=30&sort=IS_S__SEACH__KIKAKU_SORT1+asc%2CI_I__SEACH__GEN_SORT5+desc%2CI_S__SEACH__SHIKUGUN_SORT1+asc%2CIS_S__SEACH__KAKAKU_SORT+asc%2CIS_I__SEACH__KAKAKU_KBN_SORT+asc%2Crandom_50D9167F687865BE8D5F19CCAEA7ED1B.1171+desc&fl=IS_S__SEACH__AREA_CD%2CS_S__SEACH__BKN_DETAIL_INFO%2CIS_F__SEACH__BKN_IDO%2CIS_F__SEACH__BKN_KEIDO%2CS_MS__SEACH__BKN_TOKUCHO_PICT%2CIS_MS__SEACH__BKN_TOKUCHO_RS_PICT%2CIS_S__SEACH__BUKKEN_CD%2CIS_T07__SEACH__BUKKEN_NM%2CIS_S__SEACH__BUKKEN_SHU_CTG%2CIS_I__SEACH__BUS_JIKAN%2CS_S__SEACH__BUS_JIKAN_DISP%2CS_S__SEACH__CAR_KYORI_DISP%2CS_S__SEACH__CATCH_COPY%2CIS_I__SEACH__CHIKUGONENSU%2CS_S__SEACH__CHIKUNENGETSU_DISP%2CIS_I__SEACH__CM_FLG%2CS_S__SEACH__CS_GETSUGAKU_DISP%2CS_S__SEACH__EIGYO_JIKAN%2CIS_S__SEACH__EKI_CD1%2CIS_S__SEACH__EKI_CD2%2CIS_S__SEACH__EKI_CD3%2CS_S__SEACH__ENS_EKI_TOHO_INFO%2CI_MS__SEACH__ENS_HOMEN_ENSEN_CD%2CIS_T07__SEACH__FREE_WORD%2CIS_S__SEACH__GAIBU_SYSTEM_KBN%2CS_MS__SEACH__GAZO_INFO_LIST%2CS_S__SEACH__HANBAI_KOSU%2CS_S__SEACH__HANBAI_KOSU_HANTEI_FLG%2CS_S__SEACH__HIGHLIGHT_BKN_GAZO_PICT%2CS_S__SEACH__HIGHLIGHT_KBN%2CS_S__SEACH__ICHIRAN_CATCH_FLG%2CS_S__SEACH__ICHIRAN_FILE_NM%2CS_S__SEACH__ICHIRAN_FILE_NM_EXP%2CIS_T07__SEACH__JJEKI_NM%2CIS_T07__SEACH__JJENSEN_NM%2CIS_T07__SEACH__JUSHO_DISP%2CS_S__SEACH__JUSHO_MATSUBI%2CS_S__SEACH__KAIKOMUKI_DISP%2CIS_T07__SEACH__KAISHA_HP_LINK_NM_LIST%2CIS_S__SEACH__KAISHA_NM_DISP%2CS_S__SEACH__KAISHA_STAFF_DETAIL_INFO%2CS_S__SEACH__KAKAKU_DISP%2CS_S__SEACH__KANRIHI_DISP%2CIS_S__SEACH__KEISAI_KBN%2CIS_S__SEACH__KENCHIKUJOKEN_FLG%2CS_MS__SEACH__KENGAKU_KANOU_DATE%2CS_S__SEACH__KENPEI_RITSU_DISP%2CS_MS__SEACH__KIKAKU_PICT%2CS_S__SEACH__KKB_PIC_COMMENT%2CIS_MS__SEACH__KKK_KOSEI_CD_LIST%2CS_S__SEACH__KOTSU_DISP%2CIS_I__SEACH__KOTSUBIN_CD%2CI_MS__SEACH__KSK_MADORI%2CS_S__SEACH__MADORI_DISP%2CS_S__SEACH__MADORI_GAZO_NM%2CS_S__SEACH__MADORI_GAZO_NM_EXP%2CS_S__SEACH__MENKYO_NO_DISP%2CS_S__SEACH__MENSEKI1_DISP%2CS_S__SEACH__MENSEKI2_DISP%2CI_MS__SEACH__MRMH_KAISAIBI%2CIS_S__SEACH__NEW_UPDATE_FLG%2CS_S__SEACH__NYUKYO_JIKI_DISP%2CS_S__SEACH__OOAZA_NM%2CIS_S__SEACH__PROJECT_CD%2CS_S__SEACH__SAITA_KAKAKUTAI_DISP%2CIS_S__SEACH__SERVICE_SHU_CD%2CIS_S__SEACH__SHIKUGUN_KUKURI1_CD%2CIS_S__SEACH__SHIKUGUN_KUKURI2_RST_CD%2CIS_S__SEACH__SHIKUGUN_KUKURI3_CD%2CS_S__SEACH__SHIKUGUN_NM%2CS_S__SEACH__SHIRYO_SAN_FLG%2CS_S__SEACH__SHOZAICHI1_DISP%2CS_S__SEACH__SM_DETAIL_INFO%2CS_S__SEACH__SONOTA_BKN_GAZO_PICT%2CIS_MS__SEACH__SONOTA_JOKEN%2CS_S__SEACH__SOUKOSU_DISP%2CS_S__SEACH__STAFF_BKN_PR_COMMENT%2CS_S__SEACH__STAFF_PR_FLG%2CS_S__SEACH__TAB_CODE_1%2CS_S__SEACH__TAB_CODE_2%2CS_S__SEACH__TAB_CODE_3%2CS_S__SEACH__TAB_CODE_4%2CIS_MS__SEACH__TATEMONO_JOKYO_KBN%2CS_S__SEACH__TEIHO_JIKAN_DISP%2CIS_MS__SEACH__TEIKI_SHAKUTI_FLG%2CS_S__SEACH__TEIKYU_DATE%2CS_S__SEACH__TEMPO_NM_DISP%2CIS_S__SEACH__TG_NO%2CIS_MS__SEACH__THEMA_CD%2CS_S__SEACH__THEMA_CD_DETAIL_INFO%2CIS_S__SEACH__TODOFUKEN_CD%2CS_S__SEACH__TODOFUKEN_NM%2CIS_I__SEACH__TOHO_JIKAN%2CS_S__SEACH__TOHO_JIKAN_DISP%2CS_S__SEACH__TOIAWASE_JUSHO%2CS_S__SEACH__TOIAWASE_TEL_NO%2CIS_S__SEACH__TORIHIKITAIYO%2CS_S__SEACH__TOROKU_GAZO_NM1%2CS_S__SEACH__TOROKU_GAZO_NM2%2CS_S__SEACH__TOROKU_GAZO_NM3%2CS_S__SEACH__TOROKU_GAZO_NM4%2CS_S__SEACH__TSUBO_TANKA_DISP%2CS_S__SEACH__YOUSEKI_RITSU_DISP%2CIS_S__SEACH__CM_SHU_CD%2CS_S__SEACH__DOGA_ACCESS_KEY%2CIS_S__SEACH__TEMPO_KUCHIKOMI_DISP_FLG%2CS_F__SEACH__TEMPO_SOGO_SCORE%2CIS_I__SEACH__TEMPO_KUCHIKOMI_SU%2CS_I__SEACH__BKN_GAZO_COUNT%2CIS_S__SEACH__OOAZA_CD%2Cid&facet.limit=-1&facet.sort=index&facet.mincount=1&facet.field=IS_S__SEACH__SHIKUGUN_KUKURI3_CD&facet=true");
		test("q=%28IS_S__SEACH__AREA_CD%3A030+AND+%28IS_S__SEACH__GAIBU_SYSTEM_KBN%3A%2800+OR+01%29%29+AND+IS_S__SEACH__DISP_PRIORITY_FLG%3A1+AND+IS_S__SEACH__SERVICE_SHU_CD%3A011%29+AND+IS_S__SEACH__KAKAKU_MITEI_FLG%3A0&start=0&rows=0&fl=S_S__SEACH__SHIRYO_SAN_FLG%2CIS_S__SEACH__PROJECT_CD%2CIS_T07__SEACH__BUKKEN_NM%2CS_S__SEACH__BKN_DETAIL_INFO%2CS_MS__SEACH__COLUMN_FILE_NM_LIST%2CS_MS__SEACH__COLUMN_TEXT_LIST%2CS_MS__SEACH__TOKUCHO_PICT_LIST%2CS_MS__SEACH__PICT%2CS_MS__SEACH__KIKAKU_PICT%2CS_MS__SEACH__BKN_TOKUCHO_PICT%2CS_S__SEACH__SHOZAICHI1_DISP%2CS_S__SEACH__CATCH_COPY%2CIS_T07__SEACH__JJENSEN_NM%2CIS_T07__SEACH__JJEKI_NM%2CS_S__SEACH__TOHO_JIKAN_DISP%2CS_S__SEACH__BUS_JIKAN_DISP%2CS_S__SEACH__KAKAKU_DISP%2CS_S__SEACH__MENSEKI1_DISP%2CS_S__SEACH__MENSEKI2_DISP%2CS_S__SEACH__TSUBO_TANKA_DISP%2CS_S__SEACH__MADORI_DISP%2CS_S__SEACH__CHIKUNENGETSU_DISP%2CS_S__SEACH__KENPEI_RITSU_DISP%2CS_S__SEACH__YOUSEKI_RITSU_DISP%2CS_MS__SEACH__KENGAKU_KANOU_DATE%2CS_S__SEACH__COLUMN_FILE_NM1%2CS_S__SEACH__COLUMN_FILE_NM2%2CS_S__SEACH__COLUMN_FILE_NM3%2CS_S__SEACH__TOROKU_GAZO_NM1%2CS_S__SEACH__TOROKU_GAZO_NM2%2CS_S__SEACH__TOROKU_GAZO_NM3%2CS_S__SEACH__TOROKU_GAZO_NM4%2CS_S__SEACH__COLUMN_TEXT1%2CS_S__SEACH__COLUMN_TEXT2%2CS_S__SEACH__COLUMN_TEXT3%2CS_S__SEACH__COLUMN_TEXT4%2CIS_F__SEACH__BKN_KEIDO%2CIS_F__SEACH__BKN_IDO%2CIS_T07__SEACH__FREE_WORD%2CI_I__SEACH__NEW_UPDATE_SORT%2CI_S__SEACH__DISP_SEQ1%2CI_S__SEACH__DEF_SORT1%2CI_S__SEACH__DEF_SORT2%2CI_S__SEACH__GEN_SORT1%2CI_S__SEACH__GEN_SORT2%2CIS_S__SEACH__KAKAKU_SORT%2CI_S__SEACH__ENSEN_EKI_SORT%2CIS_I__SEACH__KOTSUBIN_CD%2CIS_I__SEACH__TOHO_JIKAN%2CIS_I__SEACH__BUS_JIKAN%2CIS_I__SEACH__TEIHO_JIKAN%2CI_F__SEACH__MENSEKI1%2CI_F__SEACH__MENSEKI2%2CI_S__SEACH__MADORI_SORT%2CI_F__SEACH__TSUBO_TANKA%2CI_I__SEACH__KENPEI_RITSU1%2CI_I__SEACH__KENPEI_RITSU2%2CI_I__SEACH__YOUSEKI_RITSU1%2CI_I__SEACH__YOUSEKI_RITSU2%2CI_S__SEACH__CHIKUNENGETSU%2CS_S__SEACH__TOGOGR_NO%2CIS_S__SEACH__TG_NO%2CIS_S__SEACH__AREA_CD%2CIS_MS__SEACH__KKK_KOSEI_CD_LIST%2CS_S__SEACH__ICHIRAN_FILE_NM%2CIS_S__SEACH__NEW_UPDATE_FLG%2CS_S__SEACH__BKN_CATCH_1%2CS_S__SEACH__BKN_CATCH_2%2CS_S__SEACH__BKN_CATCH_3%2CS_S__SEACH__BKN_CATCH_4%2CS_S__SEACH__TAB_CODE_1%2CS_S__SEACH__TAB_CODE_2%2CS_S__SEACH__TAB_CODE_3%2CS_S__SEACH__TAB_CODE_4%2CIS_S__SEACH__KEISAI_KBN%2CIS_MS__SEACH__EKI_CD%2CS_S__SEACH__CAR_KYORI_DISP%2CIS_S__SEACH__EKI_CD1%2CIS_S__SEACH__EKI_CD2%2CIS_S__SEACH__EKI_CD3%2CIS_I__SEACH__TOHO_JIKAN2%2CIS_I__SEACH__TOHO_JIKAN3%2CIS_I__SEACH__BUS_JIKAN2%2CIS_I__SEACH__BUS_JIKAN3%2CIS_S__SEACH__SERVICE_SHU_CD%2CI_S__SEACH__RYOUIKI_CD%2CS_S__SEACH__THEMA_CD_DETAIL_INFO%2CS_S__SEACH__TEIHO_JIKAN_DISP%2CIS_S__SEACH__GAIBU_SYSTEM_KBN%2CS_S__SEACH__ENS_EKI_TOHO_INFO%2CIS_I__SEACH__TEIHO_JIKAN2%2CIS_I__SEACH__TEIHO_JIKAN3%2Cid");
	}

	/**
	 * テストメソッド
	 * @param q
	 * @throws UnsupportedEncodingException
	 */
	public static void test(String q) throws UnsupportedEncodingException {
		String query = URLDecoder.decode(q,"UTF-8");
		String formatted = new JJ901SOLR002Action().parseQuery(URLDecoder.decode(query,"UTF-8"));
		String recover = formatted.replace("\n", "").replace("\t", "");
		if (query.equalsIgnoreCase(recover)) {
			System.out.println("-----------------------------------------------------★OK★");
			System.out.println(URLDecoder.decode(query,"UTF-8"));
			System.out.println();
			System.out.println("                 ... format ...");
			System.out.println();
			System.out.println(formatted);
		} else {
			System.err.println("-----------------------------------------------------☆NG☆");
			System.err.println(URLDecoder.decode(query,"UTF-8"));
			System.err.println();
			System.err.println("                 ... format ...");
			System.err.println();
			System.err.println(formatted);
		}
	}


	@Execute(validator = false)
	public String index() throws IOException {
		if (StringUtils.isEmpty(form.solrQuery)) {
			return "JJ901SOLR00201.jsp";
		}
		response.setContentType("text/plain; charset=UTF-8");
		PrintWriter out = response.getWriter();
		out.print(parseQuery(URLDecoder.decode(form.solrQuery,"UTF-8")));
		out.flush();
		out.close();
		return null;
	}

	/**
	 * クエリのパースとフォーマット
	 * @param solrQuery
	 * @return
	 */
	private String parseQuery(String solrQuery) {

		//１文字ずつ解析（特定文字で改行）
		List<String> lst = new ArrayList<String>();
		char[] chars = solrQuery.toCharArray();
		for (char c: chars) {
			int lstSize = lst.size();
			if (c=='(' || c==')') {
				String before = (lstSize > 0) ? lst.get(lstSize-1) : null;
				if (null != before && before.length()==0) {
					lst.set(lstSize-1, c + "");
				} else {
					lst.add(c+"");
				}
				lst.add("");
			} else if (c=='+') { //不要かも・・・
				String before = (lstSize > 0) ? lst.get(lstSize-1) : null;
				if (null != before && before.length()==0) {
				} else {
					lst.add(" ");
				}
			} else if (c=='&') {
				if (lstSize > 0) {
					if (lst.get(lstSize-1).endsWith(")")) {
						lst.add(c + "");
					} else {
						lst.set(lstSize-1, lst.get(lstSize-1) + "\n" + c);
					}
				} else {
					lst.add(c + "");
				}
			} else {
				if (lstSize > 0) {
					lst.set(lstSize-1, lst.get(lstSize-1) + c);
				} else {
					lst.add(c + "");
				}
			}
		}

		//インデント調整１
		StringBuilder sb = new StringBuilder();
		int idx = 0;
		for (String s : lst) {
			s = s.trim();
			if ("(".equals(s)) {
				idx++;
				sb.append("(\n").append(StringUtils.repeat("\t", idx));
			} else if (")".equals(s)) {
				idx--;
				sb.append("\n").append(StringUtils.repeat("\t", idx)).append(")");
			} else if ("AND".equalsIgnoreCase(s)) {
				sb.append(" And ");
			} else if ("OR".equalsIgnoreCase(s)) {
				sb.append(" Or ").append("\n").append(StringUtils.repeat("\t", idx));
			} else {
				String tab = StringUtils.repeat("\t", idx);
				if (s.startsWith("&")) s = "\n" + s;
				s = s.replaceAll(" AND ", " And \n" + tab)
						.replaceAll("^AND ", " And \n" + tab)
						.replaceAll(" AND$", " And ")
						.replaceAll(" OR ", " Or \n" + tab)
						.replaceAll("^OR ", " Or \n" + tab)
						.replaceAll(" OR$", " Or ");
				sb.append(s);
			}
		}

		//インデント調整２
		String[] lines = sb.toString().split("\n");
		sb = new StringBuilder();
		for (String line : lines) {
			if (line.startsWith("&sort=")) {
				line = line.replaceAll("&sort=", "&sort=\n\t").replaceAll(" asc,", " asc,\n\t").replaceAll(" desc,", " desc,\n\t");
			} else if (line.startsWith("&facet.field=")) {
				line = line.replaceAll("&facet.field=", "&facet.field=\n\t").replaceAll(",", ",\n\t");
			} else if (line.startsWith("&group.field=")) {
				line = line.replaceAll("&group.field=", "&group.field=\n\t").replaceAll(",", ",\n\t");
			} else if (line.startsWith("&fl=")) {
				line = line.replaceAll("&fl=", "&fl=\n\t").replaceAll(",", ",\n\t");
			}
			sb.append(line).append("\n");
		}

		// 仕上げの微調整
		return sb.toString()
				//.replaceAll("(\t+)(\\d+ Or)( \n)","$2 ") // 駅コードなどの Or 連結の改行除去 -- いまいち
				.replaceAll(" Or \n\t+\\("," Or (\n") // Or後のカッコを微調整
				.replaceAll("\n\n+","\n"); //不要改行削除
	}
}
