"""Base classes for framework/project pattern plugins."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ..._common import Symbol, Edge, GraphContext


@dataclass
class PatternEdge:
    """A directed edge produced by framework/project-specific pattern recognition.

    This is a simpler representation than the main Edge class, used specifically
    for edges generated by framework plugins.
    """

    kind: str
    from_qname: str
    to_qname: str
    file: str
    line: int
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        d = {
            "kind": self.kind,
            "from_qname": self.from_qname,
            "to_qname": self.to_qname,
            "file": self.file,
            "line": self.line,
        }
        d.update(self.metadata)
        return d


class FrameworkPlugin(ABC):
    """Abstract base class for framework/project-specific pattern plugins.

    Each plugin handles a specific framework (e.g., Struts, Spring, Django)
    or project conventions (e.g., naming patterns, directory structures).

    Plugins can contribute:
    - UI parsing: Custom template/tag parsers
    - Annotation mappings: Framework annotations → domain tags
    - Edge generation: Resolution of framework-specific relationships
    - Entry point detection: Framework-specific entry point patterns
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Plugin identifier, e.g., 'struts', 'spring', 'django'."""

    @property
    def description(self) -> str:
        """Human-readable description of what this plugin handles."""
        return ""

    @property
    @abstractmethod
    def supported_langs(self) -> list[str]:
        """List of language IDs this plugin supports, e.g., ['java'], ['python']."""

    # ── UI / Template Parsing ─────────────────────────────────────────────────

    def get_ui_file_patterns(self) -> list[str]:
        """Glob patterns for UI files this plugin handles.

        Examples:
            ["*.jsp", "**/*.html", "**/*.vue"]
            ["**/*.html", "**/*.jinja2"]

        Note: This is used when TemplatePlugin is not available.
        For full template support, consider using TemplatePlugin instead.
        """
        return []

    def parse_ui_file(self, file_path: Path, content: str) -> list[dict]:
        """Parse a UI/template file and extract structured elements.

        Args:
            file_path: Path to the file being parsed
            content: Raw file content

        Returns:
            List of element dicts with keys: kind, tag_name, attrs, line, target

        Note: This is used when TemplatePlugin is not available.
        For full template support, consider using TemplatePlugin instead.
        """
        return []

    # ── Unified Edge Production ──────────────────────────────────────────────

    def produce_edges(
        self,
        context: "GraphContext",
        lang: Optional[str] = None,
    ) -> list[dict]:
        """Produce all edges from this plugin using the shared graph context.

        This is the primary method for generating edges. Subclasses can
        override this to produce any type of edges (annotation, UI, convention).
        The context provides access to all symbols, edges, UI data, and AST.

        Args:
            context: Shared graph context with all pipeline data
            lang: Language ID (optional, for language-specific processing)

        Returns:
            List of edge dicts with keys: kind, from_qname, to_qname, file, line
        """
        edges = []

        # Framework-specific annotation edges
        edges.extend(self.resolve_annotation_edges(context))

        # Framework-specific UI edges (cross-domain)
        edges.extend(self.resolve_ui_edges(context))

        # Framework-specific convention edges
        edges.extend(self.resolve_convention_edges(context))

        return [e.to_dict() if isinstance(e, PatternEdge) else e for e in edges]

    def resolve_annotation_edges(
        self,
        context: "GraphContext",
    ) -> list[PatternEdge]:
        """Generate edges from framework-specific annotations.

        Uses GraphContext for efficient cross-file symbol lookup.

        Args:
            context: Shared graph context

        Returns:
            List of PatternEdge instances
        """
        return []

    def resolve_ui_edges(
        self,
        context: "GraphContext",
    ) -> list[PatternEdge]:
        """Generate framework-specific edges from UI/template data.

        This method handles:
        - Cross-domain edges from UI to code (e.g., JSP → Java Form class)
        - Framework-specific UI conventions

        Uses GraphContext for access to:
        - All symbols (for finding target classes)
        - All UI data (for finding related templates)
        - All AST data (for complex analysis)

        Args:
            context: Shared graph context

        Returns:
            List of PatternEdge instances
        """
        return []

    def resolve_convention_edges(
        self,
        context: "GraphContext",
    ) -> list[PatternEdge]:
        """Generate edges based on framework naming conventions.

        Uses GraphContext for access to all symbols.

        Args:
            context: Shared graph context

        Returns:
            List of PatternEdge instances
        """
        return []

    # ── Legacy Methods (deprecated, use produce_edges) ──────────────────────────

    def resolve_ui_edges_legacy(
        self,
        ui_data: dict,
        symbols: list[dict],
        ast_data: list[dict],
    ) -> list[PatternEdge]:
        """Legacy method for UI edge resolution.

        Deprecated: Use resolve_ui_edges(context) instead.
        This method is kept for backward compatibility.
        """
        return []

    # ── Annotation Mappings ─────────────────────────────────────────────────

    def get_annotation_tags(self) -> dict[str, str]:
        """Framework annotation → domain tag mappings.

        Examples:
            {"@Execute": "struts.action", "@RestController": "spring.rest_controller"}

        These are merged with LanguagePlugin annotations in stage 5.
        """
        return {}

    # ── Naming Convention Patterns ─────────────────────────────────────────

    def detect_entry_points(self, context: "GraphContext") -> list[str]:
        """Detect framework-specific entry points by naming conventions.

        Examples:
            - Java: Classes ending with "Action" with method "index()"
            - Python: Functions in "views.py" or "urls.py" patterns
            - Go: Functions with "Handler" suffix

        Args:
            context: Shared graph context

        Returns:
            List of qualified method/function names
        """
        return []

    # ── Lifecycle Hooks ────────────────────────────────────────────────────

    def on_lang_init(self, lang: str, src_root: Path) -> None:
        """Called when this plugin is initialized for a language.

        Use for one-time setup, config loading, etc.
        """
        pass

    def on_pipeline_complete(self, graph: dict) -> None:
        """Called after the full pipeline completes.

        Use for post-processing, validation, or logging.
        """
        pass
